Provide How-to guide for monitoring system metrics in a Dash application
eclipse-kanto/kanto pull request #100
Opened 2022-08-25 19:35 UTC by ognian-baruh

Provide How-to guide for System Metrics
- created a Python script that requests and receives system metrics from edge device
- created a Dash application to display the metrics from the edge device on a graph
- created a guide in the Eclipse Kanto Documentation

Signed-off-by: Ognian Baruh <Ognyan.Baruh@bosch.io>

2022-08-26 12:21 UTC, e-grigorov requested changes

2022-08-26 12:21 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/system-metrics.md
> +* {{% refn "https://plotly.com/python/getting-started/" %}}`Plotly`{{% /refn %}} installed
I would suggest to provide a link to the overview page.

2022-08-26 12:21 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/system-metrics.md
> +* {{% refn "https://dash.plotly.com/installation" %}}`Dash`{{% /refn %}} installed
I would suggest to provide a link to the overview page.

2022-08-26 12:21 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/system-metrics.md
> +To ensure that all steps in this guide can be executed, you need:
Just a question, do we need two separate bullets for plotly and dash? I think that it's more user-friendly to combine them. In this way, the user has to be only one manual installation where these tow dependencies will be installed.

2022-08-26 12:21 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/system-metrics.md
> +CPU and Memory utilization of the edge device. The location where the Python application will
- Memory -> memory
- `of the edge device` - can be removed, duplicated in the next sentence

2022-08-26 12:21 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/system-metrics.md
> +You can check out that the CPU and Memory utilization metrics are properly received and displayed
- Memory -> memory

2022-08-26 12:21 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/system-metrics.md
> +script by pressing Ctrl+C.
`You can then stop the Python script by pressing Ctrl+C.` - so far, this suggested wasn't used. It's somehow clear. Do we have special usage here? If so, it has to be moved to clean up section.

2022-08-26 12:21 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/system-metrics.md
> +by checking out the application host (by default - `127.0.0.1:8050`). You can then stop the Python
`application host` is not the right term. it's more application dashboard or something similar

2022-08-26 12:30 UTC, e-grigorov commented
@ognian-baruh The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-08-26 14:36 UTC, ognian-baruh commented
> @ognian-baruh The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances blush
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

2022-09-21 15:40 UTC, konstantina-gramatova requested changes

2022-09-21 15:40 UTC, konstantina-gramatova commented on web/site/content/docs/how-to-guides/system-metrics.md
> +  to deploy a simple HTTP server for displaying the graph and updating it in real time.
Simplify the info about Dash and Plotly in a single sentence outlining the reasoning for using them - for visualization of the data.

Also, it would be nice to align the decoration and usage of links to their official documentation for the words `Dash` and `Plotly` like it is done for e.g. `servefile` in the Upload files How-to guide [here](https://websites.eclipseprojects.io/kanto/docs/how-to-guides/upload-files/#before-you-begin).

2022-09-21 15:40 UTC, konstantina-gramatova commented on web/site/content/docs/how-to-guides/system-metrics.md
> +by checking out the application dashboard (by default - `127.0.0.1:8050`).
It would be very useful if `127.0.0.1:8050` is a link opened in a new tab with this address so that a person can just click and see the actual reported metrics directly from the how-to guide.

2022-09-26 12:05 UTC, konstantina-gramatova requested changes

2022-10-06 14:50 UTC, konstantina-gramatova approved these changes

2022-10-10 07:07 UTC, e-grigorov approved these changes

2022-10-10 07:08 UTC, merged