Provide How-to Guide for bootstrapping and connecting to the new device
eclipse-kanto/kanto pull request #102
Opened 2022-08-27 13:24 UTC by gabriela-yoncheva

[#52] Provide How-to Guide for Suite Bootstrapping
- created a Python script for handling bootstrapping request and provisioning new device
- created a guide page in the Eclipse Kanto Documentation
- created shell script for restarting Suite Connector

Signed-off-by: Gabriela Yoncheva <Gabriela.Yoncheva@bosch.io>

2022-09-01 07:11 UTC, konstantina-gramatova commented
@gabriela-yoncheva The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-09-01 21:57 UTC, gabriela-yoncheva commented
> @gabriela-yoncheva The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances 😊
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above. 🙂

2022-09-23 08:33 UTC, e-grigorov requested changes

2022-09-23 08:33 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/bootstrap-provisioning.md
> +### Provision the Eclipse Hono tenant and device
Why we need this provisioning step? It can be skipped and `Explore via Hono` can be reused. Is there a specific need?

2022-09-23 08:33 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/bootstrap-provisioning.md
> +### Configure Eclipse Kanto
Sounds so generic.

2022-09-23 08:33 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/bootstrap-provisioning.md
> +### Provision via bootstrapping
To be more close to the real setup, the python application should be prepared and started first. In this way, when the device is connected, the first request message will be sent. Is it possible with the current Hono sandbox/AMQP support?

2022-09-23 08:33 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/bootstrap-provisioning.md
> +You can check out that the Suite Connector is now connected to the new device via its log files
To use log entries for verify is somehow ugly. There is dump in the python application that can be used.

2022-09-23 08:33 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/bootstrap-provisioning.md
> +Revert the backed up `/ect/suite-connector/config.json` file.
- post bootstrapping script should be removed
- suite bootstrapping is not started by default i.e. it should be stopped here

2022-09-23 08:33 UTC, e-grigorov commented on quickstart/hono_commands_sb.py
> +    "address": "hono.eclipseprojects.io:1883",
Just an idea to use hono_ep. In this way, the how-to document can be easily adapted for another Hono instance.

2022-09-23 08:33 UTC, e-grigorov commented on quickstart/hono_commands_sb.py
> +                print('[event received from new tenant]')
It'll be useful to put some more details here because that's the final message which can be used in the verify step. Even more, the device and the tenant are automatically created and it'll be useful for the user to see details about them.

2022-09-23 08:33 UTC, e-grigorov commented on quickstart/hono_commands_sb.py
> +if ".bootstrap" not in tenant_id:
There is already a comment in the document about this check.

2022-09-23 08:33 UTC, e-grigorov commented on quickstart/hono_commands_sb.py
> +        print("Creating tenant [{}]".format(response.status_code))
It'll b useful to check the status code and on error to stop.

2022-09-23 08:33 UTC, e-grigorov commented on quickstart/hono_commands_sb.py
> +config_json_template = Template("""{
Do we need a second template for this, why not to inline in the message?

2022-09-23 08:33 UTC, e-grigorov commented on quickstart/hono_commands_sb.py
> +            data='{"ext": {'
Unify the JSON representation, the next call is using single line JSON value.

2022-09-23 08:33 UTC, e-grigorov commented on quickstart/hono_commands_sb.py
> +            new_tenant_events_thread.start()
As I can understand it, that's the response confirmation. If so, it can be too late because the device can be quick and can connect and send its messages before this confirmation. Suite connector reconnect is happing in asynchronous way.

2023-12-12 08:45 UTC, antonia-avramova commented on quickstart/hono_commands_sb.py
> +config_json_template = Template("""{
I couldn't find a more elegant way to pass json with a ":" delimiter and key-value pairs

2023-12-12 11:48 UTC, k-gostev commented on quickstart/hono_commands_sb.py
> +config_json_template = Template("""{
I think what @e-grigorov meant is to add the config in the `ditto_live_...` template like this:
```python
ditto_live_inbox_msg_template = Template("""
{
    "topic": "$namespace/$name/things/live/messages/response",
    "headers": {
        "Content-Type": "application/json",
        "correlation-id": "$correlation_id",
        "response-required": true
    },
    "path": "/features/Bootstrapping/inbox/messages/response",
    "value":
    {
        "requestId": "$request_id",
        "hash": "$hash",
        "chunk": {
            "logFile": "/var/log/suite-connector/suite-connector.log",
            "address": "mqtts://hono.eclipseprojects.io:8883",
            "caCert": "/etc/suite-connector/iothub.crt",
            "tenantId": "$tenant_id",
            "deviceId": "$device_id",
            "authId": "$auth_id",
            "password": "$password"
        }
    }
}
""")
```
And then you will have only one template and one substitution in the code.

2023-12-12 11:55 UTC, k-gostev commented on quickstart/hono_commands_sb.py
> +config_json_template = Template("""{
But then this needs to be base64 encoded:
```python
        chunk_hash = hashlib.sha256(chunk.encode())
        chunk = base64.b64encode(chunk.encode()).decode('ascii')
```
So, I guess you can leave it as it is.

2023-12-12 12:01 UTC, k-gostev requested changes
Copyright dates should be changed.

2023-12-12 12:02 UTC, k-gostev commented
@antonia-avramova please also rebase the changes

2023-12-12 12:22 UTC, k-gostev requested changes

2023-12-12 12:22 UTC, k-gostev commented on web/site/content/docs/how-to-guides/bootstrap-device.md
> +Following the steps below you will automatically provision a new device via a publicly available Eclipse Hono sandbox using Eclipse Kanto.
```suggestion
By following the steps below you will automatically provision a new device via a publicly available Eclipse Hono sandbox using Eclipse Kanto.
```

2023-12-12 12:22 UTC, k-gostev commented on web/site/content/docs/how-to-guides/bootstrap-device.md
> +provided to explore the capabilities for device bootstrapping and automatically provision new device.
```suggestion
provided to explore the capabilities for device bootstrapping and automatically provision а new device.
```

2023-12-12 12:22 UTC, k-gostev commented on web/site/content/docs/how-to-guides/bootstrap-device.md
> +  post bootstrap {{% /refn %}}
```suggestion
  post bootstrap script{{% /refn %}}
```

2023-12-12 12:22 UTC, k-gostev commented on web/site/content/docs/how-to-guides/bootstrap-device.md
> +Open file `/etc/suite-connector/config.json`, copy `tenantId`, `deviceId`, `authId` and `password`
```suggestion
Open file `/etc/suite-connector/config.json`, copy `tenantId`, `deviceId`, `authId` and `password`.
```

2023-12-12 12:22 UTC, k-gostev commented on web/site/content/docs/how-to-guides/bootstrap-device.md
> +Update it with previous copied settings and with following:
```suggestion
Update the configuration as shown below and replace `tenantId`, `deviceId`, `authId` and `password` with the settings that you copied in the previous step.
```

2023-12-13 08:10 UTC, dimitar-dimitrow requested changes

2023-12-13 08:10 UTC, dimitar-dimitrow commented on quickstart/hono_commands_sb.py
> +new_password = os.environ.get("PASSWORD") or opts_dict['-p']
The command arguments must have greater priority than environment variables.
```suggestion
tenant_id = opts_dict['-t'] or os.environ.get("TENANT")
device_id = opts_dict['-d'] or os.environ.get("DEVICE_ID")
new_password = opts_dict['-p'] or os.environ.get("PASSWORD")
```

2023-12-18 08:37 UTC, k-gostev approved these changes

2023-12-19 08:48 UTC, dimitar-dimitrow approved these changes

2023-12-19 09:07 UTC, merged