File backup reference guide
eclipse-kanto/kanto pull request #107
Opened 2022-08-30 13:24 UTC by velitchko-valkov

[#89] File backup reference guide 
 - Provided the information relevant to available configurations per a Kanto File Backup instance
 - Added an example of how to use this configuration
 - Added an example of a generic configuration

Signed-off-by: Velitchko Valkov <Velitchko.Valkov@bosch.io>

2022-08-30 14:11 UTC, konstantina-gramatova commented
@velitchko-valkov The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-08-31 05:20 UTC, e-grigorov requested changes

2022-08-31 05:20 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +    "type": "directory",
The type default value is "file" that mean all from from "dir" specified directory. I would suggest to remove the type from the minimal required configuration.

2022-08-31 05:20 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +    "dir": "/var/tmp/file-backup/myBackupDirectory",
myBackupDirectory - do we need this sub-directory? /var/tmp/file-backup is a specific directory for file-backup.

2022-08-31 05:20 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +Be aware that some combinations may require property removal.
Is this warning valid for the file-backup? I guess not and it should be removed.

2022-08-31 05:20 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +  Customize the file backup to and from a backend storage.
Just a note that file backup is described with the same wording.

2022-09-01 07:15 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +Be aware that some combinations may require property removal.
It is - the reason is that if backupCmd and restoreCmd are set, the 'dir' property is not used.

2022-09-01 07:16 UTC, velitchko-valkov commented
> @velitchko-valkov The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances 😊
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

 I understand and agree with the license change explained above.

2022-09-01 07:18 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +weight: 7
Okay, I can place it with weight 6, and put the System Metrics reference guide to be with weight 7. Note that File Upload has weight 5.

2022-09-01 07:22 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +### Properties
Okay,I will remove all full stops

2022-09-01 07:24 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +| **Auto upload** | | | |
Yes, I will fix it

2022-09-01 07:25 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +| broker | string | tcp://localhost:1883 | Address of the MQTT server/broker that the file upload will connect for the local communication, the format is: `scheme://host:port`. |
I will fix it.

2022-09-01 07:26 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +| logFile | string | log/file-upload.log | Path to the file where log messages are written. |
Right now, the file used for the logging is file-upload.log. I tested it

2022-09-01 07:27 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +| stopTimeout | string | 30s | Time to wait for running uploads/backups to finish as a sequence of decimal numbers, each with optional fraction and a unit suffix, such as: 300ms, 1.5h, 10m30s, etc.,
Yes, I will fix this.

2022-09-01 07:27 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +    "type": "directory",
Alright.

2022-09-01 07:27 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +    "dir": "/var/tmp/file-backup/myBackupDirectory",
It is not necessary,I can remove it.

2022-09-01 07:28 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +  Customize the file backup to and from a backend storage.
Should we make any changes here?

2022-09-01 07:39 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +| checksum | bool | false | Send MD5 checksum for uploaded files to ensure data integrity. Computing checksums incurs additional CPU/disk usage. |
Alright.

2022-09-01 11:37 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +| type | string | file | Type of the files that are uploaded by this feature. |
I will fix this.

2022-09-01 11:37 UTC, velitchko-valkov commented on web/site/content/docs/references/file-backup-config.md
> +| context | string | edge |Context of the files uploaded by the feature, unique in the scope of the type. |
I will fix this.

2022-09-02 07:05 UTC, e-grigorov requested changes

2022-09-02 07:05 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +The minimal required configuration that backs up a directory from the file system.
Actually, this configuration will not backed up the directory, it'll enable the possibility to do so from the cloud. The wording can be enriched: that enables...

2022-09-02 07:05 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +
Redundant empty line.

2022-09-23 12:52 UTC, e-grigorov requested changes

2022-09-23 12:52 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +| type | string | file | Type of the files that are backed up by this feature |
It'll be useful to align the property order with the file upload because there are same/similar properties.

2022-09-23 12:52 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +| mode | string | strict | Restriction on files that can be dynamically selected for a backup, the supported modes are: strict, lax and scoped |
Is it restriction on files or it's restriction on directories here?

2022-09-23 12:52 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +```json
The configuration has to be aligned with the last one where we have the storage property.

2022-09-23 12:52 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +The minimal required configuration that enables backing up a directory from the file system.
The example should do something more than copy/paste of the default config. I would suggest to align at least with the file upload i.e. to set the type to something important.

2022-09-23 13:23 UTC, e-grigorov requested changes

2022-09-23 13:23 UTC, e-grigorov commented on web/site/content/docs/references/file-backup-config.md
> +  Customize the file backup and recovery to and from a backend storage.
I know that I asked about this recovery but it sounds strange and I would suggest to step back to: restore.

2022-09-27 11:03 UTC, konstantina-gramatova approved these changes

2022-09-27 11:05 UTC, e-grigorov approved these changes

2022-09-27 11:08 UTC, merged