Update Container Management reference guide
eclipse-kanto/kanto pull request #112
Opened 2022-09-08 07:35 UTC by dimitar-dimitrow

#104 add image_expiry configuration

Signed-off-by: Dimitar Dimitrov <dimitar.dimitrov3@bosch.io>

2022-09-16 13:59 UTC, e-grigorov requested changes
The final fix contains one property more: image_expiry_disable and the descriptions have to be aligned.

2022-09-19 12:53 UTC, e-grigorov requested changes

2022-09-19 12:53 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-manager-config.md
> +| image_expiry | string | 744h | Expiry time for images, the time that unused images and its content would stay locally cached, the format is: `72h3m0.5s` |
The CLI command descriptions says: Specify the time period for the cached images and content to be kept in the form of e.g. 72h3m0.5s

I wouldn't say use the same description here because we have context i.e. don't start with the action etc. but the same wording should be used.

2022-09-19 12:53 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-manager-config.md
> +| image_expiry_disable | bool | false | Disables expiry of cached images and content |
- Disables -> Disable
- Align the wording with CLI description

2022-09-19 14:03 UTC, e-grigorov requested changes

2022-09-19 14:03 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-manager-config.md
> +| image_expiry | string | 744h | Time period for the cached images and content to be kept, the format is: `72h3m0.5s` |
> the format is: `72h3m0.5s`

Actually, that's not a format but an example. The description should be adjusted.

2022-09-19 14:45 UTC, e-grigorov approved these changes

2022-09-19 14:53 UTC, konstantina-gramatova approved these changes

2022-09-19 14:54 UTC, e-grigorov requested changes

2022-09-19 14:54 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-manager-config.md
> +| image_expiry | string | 744h | Time period for the cached images and content to be kept in the form of e.g. `72h3m0.5s` |
`72h3m0.5s` - because it's a value, do we need the code formatting? There are no other examples.

2022-09-19 15:05 UTC, e-grigorov approved these changes

2022-09-19 15:06 UTC, merged