Added cloud2edge setup script for integration testing
eclipse-kanto/kanto pull request #127
Opened 2022-09-13 12:22 UTC by nzhechev-bosch

[#126] Add cloud2edge setup script for integration testing

Signed-off-by: Nikola Zhechev <Nikola.Zhechev@bosch.io>

2022-09-14 18:02 UTC, refi64 commented on integration/c2esetup/main.go
> +	registryAPI := fmt.Sprintf("http://%s:%d/v1", c2eCfg.RegistryHost, c2eCfg.RegistryPort)
Could some configuration options be added for if the registry is behind basic authentication? Our c2e instance uses an authenticated registry to avoid concerns with abuse.

2022-09-14 18:02 UTC, refi64 commented on integration/c2esetup/main.go
> +	cfg.CaCert = "/etc/suite-connector/iothub.crt"
Is this path intended to be hardcoded?

2022-09-15 07:19 UTC, nzhechev-bosch commented on integration/c2esetup/main.go
> +	registryAPI := fmt.Sprintf("http://%s:%d/v1", c2eCfg.RegistryHost, c2eCfg.RegistryPort)
Will do.

2022-09-15 07:22 UTC, nzhechev-bosch commented on integration/c2esetup/main.go
> +	cfg.CaCert = "/etc/suite-connector/iothub.crt"
Good catch! I'll make it configurable.

2022-09-16 01:10 UTC, refi64 commented on integration/c2esetup/main.go
> +	registryAPI := fmt.Sprintf("http://%s:%d/v1", c2eCfg.RegistryHost, c2eCfg.RegistryPort)
Would it be possible to add service-specific support for using secure protocols (http -> https, tcp -> ampqs)? That way we could also test to make sure the certificate setup is correct on client & server!

2022-09-16 05:50 UTC, nzhechev-bosch commented on integration/c2esetup/main.go
> +	registryAPI := fmt.Sprintf("http://%s:%d/v1", c2eCfg.RegistryHost, c2eCfg.RegistryPort)
Sure, will do.

2022-10-19 17:14 UTC, refi64 commented on integration/c2esetup/main.go
> +	if err := copyFile(configFile, configFileBackup); err != nil {
This is definitely just "nice to have" territory, but we're running c2esetup on CI separately from the main test binary, so it would be nice if we could skip the step of writing the config file there entirely (maybe if `-configFile` is set to be some magic `none` value or similar?).

2022-10-19 17:17 UTC, refi64 commented on integration/c2esetup/main.go
> +			code = restartSuiteConnector()
Ditto as above for being able to skip the restart.

2022-10-31 08:17 UTC, e-grigorov requested changes

2022-10-31 08:17 UTC, e-grigorov commented on integration/c2esetup/main.go
> +		honoDevices := &honoThings{}
The naming is not aligned. On a single line, there is: honoDevices := &honoThings{}
In the end, we have Hono devices, not things.

2022-10-31 08:17 UTC, e-grigorov commented on integration/c2esetup/main.go
> +			fmt.Println(err)
The error handling is not correct. In case of an error, the loop will be executed. It doesn't seem to be correct.

2022-10-31 08:17 UTC, e-grigorov commented on integration/c2esetup/main.go
> +			if strings.HasPrefix(thing.Id, deviceIDPrefix) {
It'll work for Kanto but more stable approach can be used which will check for gateway <-> device relation.

2022-10-31 08:17 UTC, e-grigorov commented on integration/c2esetup/main.go
> +func deleteDittoDevices(deviceIDPrefix string) {
Ditto things, not devices. In general, I would suggest to merge this method with Hono cleanup. The reason is that Hono provides gateway <-> device relation. Based on this relation, the device ID can be collected from Hono and the thing with the same ID can be removed from Ditto. That's the opposite of auto-creation mechanism.

2022-10-31 08:17 UTC, e-grigorov commented on integration/c2esetup/main.go
> +	fileFlags = 0666
In general, we should not override the the file flags but keep the existing.

2022-10-31 08:17 UTC, e-grigorov commented on integration/c2esetup/main.go
> +		if err := copyFile(configFileBackup, configFile); err != nil {
Do we need to remove the backup file?

2022-10-31 08:41 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/go.mod
> +module c2esetup
Thanks, I will read the guide and will suggest a possible solution.

2022-10-31 08:42 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	if err := copyFile(configFile, configFileBackup); err != nil {
That would be possible. Our goal was to be able to revert the service in a pristine state when cleaning up, and for that purpose we want to save a backup copy of the original file, so that we can restore it. I don't see any issue with making this possible to opt-out of.

2022-10-31 08:43 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +			code = restartSuiteConnector()
Sounds reasonable. This is done because suite-connector.service doesn't pick up configuration file changes until it's restarted, but I see no problem with making it possible to opt-out.

2022-10-31 08:45 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	mqtt "github.com/eclipse/paho.mqtt.golang"
Thank you for noticing this, we need to keep the codebase consistent.

2022-10-31 08:46 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	cleanup := flag.Bool("cleanup", false, "Clean up test resources")
What about cleanUp?

2022-10-31 08:47 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +			fmt.Printf("forcing deviceID \"%s\"\n", deviceID)
My thinking was that I should print out the command-line parameter name, but it's not consistent throughout the file. I will change it to `device id`.

2022-10-31 08:54 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +					fmt.Printf(", overriding %s", deviceID)
I have found it useful to use the tool to delete devices which I've created manually. But maybe it complicates the logic too much here.

2022-10-31 08:56 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +		return
It is here as a precaution.

2022-10-31 09:01 UTC, e-grigorov commented on integration/c2esetup/main.go
> +	cleanup := flag.Bool("cleanup", false, "Clean up test resources")
I proposed `clean` just because I can provide bunch of examples: mvn clean, git clean etc.

2022-10-31 09:04 UTC, e-grigorov commented on integration/c2esetup/main.go
> +		return
To me, it seems to be dead code.

2022-10-31 11:52 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/go.mod
> +module c2esetup
From: https://github.com/golang/go/wiki/Modules
`Good package names are short and clear. They are lower case, with no under_scores or mixedCaps.`
I am going to fix the module name to be `kanto/integration/c2esetup` as per the linked guide about multi-module repositories.

2022-10-31 13:08 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	RegistryAddress string
Sounds good, this will affect all other tests as well because these are linked to environment variables.

2022-10-31 13:53 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +			if strings.HasPrefix(thing.Id, deviceIDPrefix) {
How can we find the related hono devices and ditto things?

2022-10-31 13:54 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	type honoThing struct {
Can we use the Hono and Ditto names here? If yes, then I'll use the terms honoDevice(s)/device(s) and dittoThing(s)/thing(s).

2022-10-31 13:55 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	fileFlags = 0666
I am going to check if the file already exists. If it does, I'll keep the existing flags of the previous file, but if it doesn't, then I'll use the declared constant flags from here.

2022-10-31 13:55 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +		if err := copyFile(configFileBackup, configFile); err != nil {
That is a good question. Most likely yes, I'll implement that.

2022-11-01 07:13 UTC, e-grigorov commented on integration/c2esetup/main.go
> +func deleteDependentDevices(deviceIDPrefix string) {
Did you have the opportunity to check the specification and how the device are named there?

2022-11-01 08:12 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +func deleteDependentDevices(deviceIDPrefix string) {
The JSON attribute is called 'via'.

2022-11-01 08:31 UTC, e-grigorov commented on integration/c2esetup/main.go
> +			if strings.HasPrefix(thing.Id, deviceIDPrefix) {
Clean up is the opposite of the bootstrapping operation. How does it work? There are a few steps:
- Hono device (as gateway) is created
- Ditto thing is created for this gateway device

and the implicit creation works in a similar way i.e.
- Hono device (via gateway) is automatically created
- Ditto thing is created for this device

Clean up should do the opposite:
- Get all device via the gateway from Hono
- Get all things for these devices and remove them
- Remove Hono devices
- Remove Ditto gateway thing
- Remove Hono device

2022-11-01 08:34 UTC, e-grigorov commented on integration/c2esetup/main.go
> +	type honoThing struct {
In general, I don't like the idea to use the project names. I'll provide another example, instead MQTT, do you think that Paho has to be used? It's the same here.

2022-11-02 23:48 UTC, refi64 commented on integration/c2esetup/main.go
> +		readIdsFromMQTT()
Shouldn't this use the device ID if one is given? It prevents the need to have the MQTT broker local, but also keeps it more consistent with the creation behavior (where -device "overrides" the default mechanism).

2022-11-03 15:20 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	if err := copyFile(configFile, configFileBackup); err != nil {
If the config file is set to the empty string (e.g. `""` in shell), now the configuration file writing, and the restarting of suite-connector.service will be skipped. Also if the config file backup is set to the empty string, the saving and restoring of backup will be skipped.

2022-11-03 15:22 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +		readIdsFromMQTT()
Done

2022-11-08 08:16 UTC, e-grigorov commented on integration/c2esetup/go.mod
> +module c2esetup
- `Good package names are short and clear. They are lower case, with no under_scores or mixedCaps.` - why are we talking about the package names here? Here, we have only one package and that's the `main`. The topic is not relevant.
- The proposed module path doesn't follow the convention. I'll try to simplify the topic and I hope that we'll be able to finalize it. The go.mod file is located in: github.com/eclipse-kanto/kanto/integration/c2esetup/go.mod. Is there a reason not to use: `github.com/eclipse-kanto/kanto/integration/c2esetup` as a module path?

2022-11-08 08:35 UTC, e-grigorov commented on integration/c2esetup/main.go
> +	flag.StringVar(&tenantID, "tenant", "", "Hono tenant ID")
Did you check the provided documentation, there are:
- `tenantId`, not `tenant`
- `deviceId`, not `device`
- `policyId`, not `policy`

2022-11-08 10:26 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +			fmt.Println(err)
Fixed

2022-11-08 10:28 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	fileFlags = 0666
Done

2022-11-08 10:28 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +		if err := copyFile(configFileBackup, configFile); err != nil {
Done

2022-11-08 10:28 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +			if strings.HasPrefix(thing.Id, deviceIDPrefix) {
Done

2022-11-08 10:28 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	flag.StringVar(&logFile, "logFile", "/var/log/suite-connector/suite-connector.log", "Path for Suite Connector log file")
Done

2022-11-08 10:28 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	flag.StringVar(&deviceID, "deviceID", "", "Test device ID, defaults to randomly generated. You should not use this param in a LAVA setting")
Done

2022-11-18 13:03 UTC, e-grigorov commented on integration/c2esetup/main.go
> +	if err := copyFile(configFile, configFileBackup); err != nil {
@dimiter-todorov-georgiev - why not just to make this flag optional? In any case, the usage message has to be updated.

2022-11-18 15:33 UTC, e-grigorov commented on integration/c2esetup/main.go
> +func deleteDependentDevices(deviceIDPrefix string) {
JSON attribute is called `via` but the semantic behind is:
```
The device IDs of the gateways that are registered to act on behalf of this device. Note that "via" and "memberOf" must not be set at the same time.
```

2022-11-23 09:59 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +	if err := copyFile(configFile, configFileBackup); err != nil {
Done

2022-11-23 10:00 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/main.go
> +			code = restartSuiteConnector()
Updated the help message

2022-11-23 10:02 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/go.mod
> +module c2esetup
I'll change it to c2e-setup ( i.e. github.com/eclipse-kanto/kanto/integration/c2e-setup )

2022-11-23 10:15 UTC, dimiter-todorov-georgiev commented on integration/c2esetup/go.mod
> +module c2esetup
Done.

2022-11-28 09:20 UTC, e-grigorov requested changes

2022-11-28 12:01 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +		mqttClient, err := util.NewMQTTClient(&cfg)
Done.

2022-11-28 12:01 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	if err == nil {
Done.

2022-11-28 12:01 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +				deleteResources(resources[:i])
Done.

2022-11-28 12:02 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	DeviceRegistryAPIAddress string `env:"DEVICE_REGISTRY_API_ADDRESS" envDefault:""`
Done.

2022-11-28 12:02 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	MqttAdapterAddress string `env:"MQTT_ADAPTER_ADDRESS" envDefault:""`
Done.

2022-11-28 12:02 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +		fmt.Printf("failed to process command-line arguments: %v\n", err)
Done.

2022-11-28 12:02 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +			fmt.Printf("unable to open local mqtt connection to %s\n", cfg.LocalBroker)
Done.

2022-11-28 12:02 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +		os.Exit(1)
Done.

2022-11-28 12:02 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	fmt.Println("checking if the device was successfully created in the registry")
Done.

2022-11-28 12:02 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	if err == nil {
Done.

2022-11-28 12:04 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +		if strings.Contains(devicesJSON, "status") &&
Done. I've removed these checks because we just want to see if this name is used or not. If the name is used, we need to stop trying to create the device and let the user try with another (randomly generated or not) name. Since we no longer check if the device is created successfully at the end, we don't need to check the contents of the response any more, only if one was received successfully or not.

2022-11-28 12:05 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	return ioutil.WriteFile(dst, data, mode)
Replaced with the recommended calls from the os package, as per https://github.com/go-critic/go-critic/issues/1019

2022-11-28 12:06 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	mode := getFileModeOrDefault(dst, configDefaultMode)
I've changed the logic this way:
1. get the file mode of the source file.
2. get the file mode of the destination file, using the file mode of the source file as default, in case the destination file is missing

This way, if the destination file is missing, it will assume the file mode of the source file.
But if the destination file is present, it will keep its own file mode.

2022-11-28 12:06 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +func deleteDigitalTwinAPIThings(relations []string) {
Done.

2022-11-28 12:06 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +func deleteDigitalTwinAPIThings(relations []string) {
Done.

2022-11-28 12:06 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	fmt.Println("deleting automatically created things in the digital twin API...")
Done.

2022-11-28 12:06 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +		fmt.Println(err)
Done.

2022-11-28 12:06 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +			fmt.Println(err)
Done.

2022-11-28 12:07 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	err = ioutil.WriteFile(path, jsonContents, mode)
Replaced with the recommended calls from the os package, as per https://github.com/go-critic/go-critic/issues/1019

2022-11-28 12:07 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +		code = -1
Done.

2022-11-28 14:23 UTC, e-grigorov commented on integration/c2e-setup/main.go
> +		defer mqttClient.Disconnect(500)
Is there a reason not to use TestConfiguration.MqttQuiesceMs?

2022-11-28 14:41 UTC, e-grigorov commented on integration/c2e-setup/main.go
> +	if err != nil {
Use just else here.

2022-11-28 15:36 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	if err != nil {
err gets assigned in the above if, so we need to re-check here.

2022-11-28 16:00 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +		defer mqttClient.Disconnect(500)
Done.

2022-11-29 08:13 UTC, e-grigorov commented on integration/c2e-setup/main.go
> +	if !*clean {
No need to duplicated the if check here, the asserts can be moved to `if !*clean {` above.

2022-11-29 08:16 UTC, e-grigorov commented on integration/c2e-setup/main.go
> +	resources := make([]*resource, 0, 4)
There are 3 append operations, I guess that capacity can be set to 3.

2022-11-29 08:20 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	resources := make([]*resource, 0, 4)
Done.

2022-11-29 08:22 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	if !*clean {
Done.

2022-11-29 08:24 UTC, e-grigorov commented on integration/c2e-setup/main.go
> +	deleteResources(resources)
Errors in the resource clean up are ignored. Do we need to handle this?

2022-11-29 08:38 UTC, e-grigorov commented on NOTICE.md
> +golang.org/x/crypto (v0.0.0-20190308221718-c2843e01d9a2)
The notice has to be updated. All dependencies which are included in the binary has to be declared.

2022-11-29 11:07 UTC, dimiter-todorov-georgiev commented on integration/c2e-setup/main.go
> +	deleteResources(resources)
Done

2022-11-29 11:07 UTC, dimiter-todorov-georgiev commented on NOTICE.md
> +golang.org/x/crypto (v0.0.0-20190308221718-c2843e01d9a2)
Done

2022-11-29 15:49 UTC, e-grigorov approved these changes

2022-11-29 15:52 UTC, merged