Provide RPM support
eclipse-kanto/kanto pull request #129
Opened 2022-09-15 11:34 UTC by konstantina-gramatova

[#85] Provide RPM support

Added RPM packaging and relevant resources - scripts, builds, packaging config.

Signed-off-by: Konstantina Gramatova <konstantina.gramatova@bosch.io>

2022-09-15 11:38 UTC, dimiter-todorov-georgiev commented
The build with goreleaser passes. The RPM successfully deploys on Fedora-IOT x64 and the DEB file successfully deploys on Raspbian/arm64.

2022-09-15 11:39 UTC, konstantina-gramatova commented
Thank you @dimiter-todorov!

2022-09-16 13:25 UTC, e-grigorov requested changes

2022-09-16 13:25 UTC, e-grigorov commented on build/prerm_rpm
> +    # Package removal, not upgrade
On removal, the suite connector mosquitto configuration is removed, I guess that the mosquitto service has to be restarted.

2022-09-16 13:25 UTC, e-grigorov commented on build/postinst_rpm
> +    echo "include_dir /etc/mosquitto/conf.d" >> /etc/mosquitto/mosquitto.conf
If mosquitto service is already there, do we need explicit restart to apply the new configuration?

2022-09-16 13:25 UTC, e-grigorov commented on build/postinst_rpm
> +    /usr/lib/systemd/systemd-update-helper install-system-units suite-connector.service || :
If enabled, can we auto-start them? What's the RPM expected behavior?

2022-09-16 13:49 UTC, dimiter-todorov-georgiev commented on build/postinst_rpm
> +    /usr/lib/systemd/systemd-update-helper install-system-units suite-connector.service || :
It's expected not to start them.

2022-09-16 13:49 UTC, dimiter-todorov-georgiev commented on build/postinst_rpm
> +    echo "include_dir /etc/mosquitto/conf.d" >> /etc/mosquitto/mosquitto.conf
Yes, I think so.

2022-09-16 13:50 UTC, dimiter-todorov-georgiev commented on build/prerm_rpm
> +    # Package removal, not upgrade
Maybe so. I think it should be able to keep running with the existing configuration, even though the files have been removed, until the next time that mosquitto is restarted. 

Maybe we should restart it here.

On the other hand, maybe we shouldn't touch a service that isn't getting uninstalled right now.

2022-09-16 13:51 UTC, e-grigorov commented on build/postinst_rpm
> +    /usr/lib/systemd/systemd-update-helper install-system-units suite-connector.service || :
Basically, this means that they will not be started right after the installation but after the first system reboot. It sounds strange, is there a doc reference?

2022-09-16 13:55 UTC, e-grigorov commented on build/prerm_rpm
> +    # Package removal, not upgrade
But the service is going to operate with obsolete configuration. In any case, it seems that Debian package does so: https://github.com/eclipse-kanto/kanto/blob/main/build/postrm

2022-09-16 15:27 UTC, dimiter-todorov-georgiev commented on build/postinst_rpm
> +    /usr/lib/systemd/systemd-update-helper install-system-units suite-connector.service || :
I'm not sure if there's an actual doc, but they are not suggesting that .preset files are distributed in the same rpm as the services, which we're doing here.

2022-09-16 15:27 UTC, dimiter-todorov-georgiev commented on build/prerm_rpm
> +    # Package removal, not upgrade
Done

2022-09-16 15:27 UTC, dimiter-todorov-georgiev commented on build/postinst_rpm
> +    echo "include_dir /etc/mosquitto/conf.d" >> /etc/mosquitto/mosquitto.conf
Done

2022-09-19 07:21 UTC, e-grigorov requested changes

2022-09-19 07:21 UTC, e-grigorov commented on build/prerm_rpm
> +    # Package removal, not upgrade
> Done

What do you mean? Mosquitto is still not restarted in the post remove script.

2022-09-19 07:21 UTC, e-grigorov commented on build/postinst_rpm
> +    /usr/lib/systemd/systemd-update-helper install-system-units suite-connector.service || :
I agree about the preset but I am asking about auto-start if enabled. Is it possible to do so with the current helpers? If marked for restart or?

2022-09-19 07:21 UTC, e-grigorov commented on build/postinst_rpm
> +    echo "include_dir /etc/mosquitto/conf.d" >> /etc/mosquitto/mosquitto.conf
> Done

Now, the suite-connector is restarted but my comment was about the mosquitto. Why is it?

2022-09-19 09:30 UTC, dimiter-todorov-georgiev commented on build/postinst_rpm
> +    echo "include_dir /etc/mosquitto/conf.d" >> /etc/mosquitto/mosquitto.conf
This was a mistake, sorry!

2022-09-19 09:30 UTC, dimiter-todorov-georgiev commented on build/postinst_rpm
> +    /usr/lib/systemd/systemd-update-helper install-system-units suite-connector.service || :
We will check if the service is enabled using the systemctl command, and then start the service if it's enabled.

2022-09-19 09:31 UTC, dimiter-todorov-georgiev commented on build/postinst_rpm
> +    echo "include_dir /etc/mosquitto/conf.d" >> /etc/mosquitto/mosquitto.conf
This was an error. Will be fixed.

2022-09-19 09:31 UTC, dimiter-todorov-georgiev commented on build/prerm_rpm
> +    # Package removal, not upgrade
This was an error. Will be fixed.

2022-09-21 07:08 UTC, e-grigorov approved these changes

2022-09-21 07:10 UTC, merged