[#90] Provide How-to guide for backing up and restoring a text file
eclipse-kanto/kanto pull request #142
Opened 2022-09-23 16:23 UTC by ognian-baruh

Provide How-to guide for File Backup module of Eclipse Kanto
- created Python scripts that executes the backup and restore operations
- created a guide in the Eclipse Kanto Documentation

Signed-off-by: Ognian Baruh <Ognyan.Baruh@bosch.io>

2022-09-30 11:17 UTC, e-grigorov requested changes

2022-09-30 11:17 UTC, e-grigorov commented on quickstart/hono_commands_fb.py
> +print('[starting] demo file upload app for tenant [{}], device [{}] at [{}]'.format(tenant_id, device_id, uri))
`file upload` -> `file backup`

2022-09-30 11:17 UTC, e-grigorov commented on quickstart/hono_commands_fb.py
> +    print('[stopping] demo file upload app for tenant [{}], device [{}] at [{}]'.format(tenant_id, device_id, uri))
`file upload` -> `file backup`

2022-10-03 13:18 UTC, ognian-baruh commented on quickstart/hono_commands_fb.py
> +
According to PEP8 Style guide for Python code and more specifically the section about [Blank lines](https://peps.python.org/pep-0008/#blank-lines), top-level function and class definitions should be surrounded with two blank lines. Removing this blank line would cause a warning: "PEP 8: E305 expected 2 blank lines after class or function definition, found 1". Considering this, should I remove it or should it stay?

2022-10-03 13:21 UTC, ognian-baruh commented on quickstart/hono_commands_fb.py
> +    print('[stopping] demo file upload app for tenant [{}], device [{}] at [{}]'.format(tenant_id, device_id, uri))
Wouldn't it be better if it was `file backup and restore` as this script is used for both operations?

2022-10-03 13:33 UTC, ognian-baruh commented on quickstart/hono_commands_fb.py
> +            elif body["topic"].split("/")[-1] == "modify" and body["path"].split("/")[-1] == "lastUpload":
`lastUpload` comes as an event after `lastOperation`, because `lastOperation` reflects whether the backup file is prepared, as `lastUpload` reflects the state of the file upload itself. Wouldn't it make more sense if we made sure the file was successfully uploaded before terminating the script?

2022-10-04 09:32 UTC, ognian-baruh commented on web/site/content/docs/how-to-guides/backup-restore.md
> +Following the steps below you will back up a simple text file to an HTTP file server
I researched a little bit regarding "a" or "an" in front of HTTP and the majority of the opinions were, that it should be "an", because the "H" is pronounced as "eich". I am not really sure which is the better option.

2022-10-04 09:55 UTC, ognian-baruh commented on quickstart/hono_commands_fb.py
> +            value = json.dumps(dict(correlationId=self.correlation_id, dir="./", storage="storage"))
The `dir` parameter of the payload for the backup command points to the directory, which will be backed up. When starting the file-backup binary with the mode from the default configuration of the executable, which is `scoped`, the directory which will be backed up is set in the configuration file for the executable. When the `dir` parameter of the payload for the backup command is set, it points to a subdirectory of the directory which is set in the `config.json` file. The default value is `./`, which means there is no need to explicitly set the `dir` parameter and will be removed from the payload.
The `storage` parameter points to the directory, where to archive is kept prior to uploading it. It has a value in the configuration file of the executable, which makes it unnecessary for it to be present in the payload of the command and is also removed.
The payload will be set the following way:
`value = json.dumps(dict(correlationId=self.correlation_id))`

2022-10-04 10:11 UTC, ognian-baruh commented on quickstart/hono_commands_fb.py
> +            upload_options = {"https.url": "http://localhost:8080/data.zip"}
Regarding the second comment - is it okay to pass the host as an argument to the Python script, the same way the `tenantId` and `deviceId` are passed as argument?
If yes, then shouldn't this be implemented into the File Upload How-to guide, where the URL is static as well?

2022-10-04 11:03 UTC, ognian-baruh commented on quickstart/hono_commands_fb.py
> +            upload_options = {"https.url": "http://localhost:8080/data.zip"}
Regarding the first comment - the body in the `else` statement is used for two commands - "start" and "restore", in the first case the operation is upload, in the other - it is download. Should I rename the variable to `options` or is better to split the `else` into two for better readability?

2022-10-05 11:59 UTC, e-grigorov commented on quickstart/hono_commands_fb.py
> +            upload_options = {"https.url": "http://localhost:8080/data.zip"}
> Regarding the second comment - is it okay to pass the host as an argument to the Python script, the same way the `tenantId` and `deviceId` are passed as argument? If yes, then shouldn't this be implemented into the File Upload How-to guide, where the URL is static as well?

Sure, that's why we have this ticket: #157

2022-10-05 12:53 UTC, e-grigorov commented on quickstart/hono_commands_fb.py
> +            upload_options = {"https.url": "http://localhost:8080/data.zip"}
> Regarding the first comment - the body in the `else` statement is used for two commands - "start" and "restore", in the first case the operation is upload, in the other - it is download. Should I rename the variable to `options` or is better to split the `else` into two for better readability?

Just `options` should be ok.

2022-10-05 14:30 UTC, e-grigorov commented on quickstart/hono_commands_fb.py
> +            elif body["topic"].split("/")[-1] == "modify" and body["path"].split("/")[-1] == "lastUpload":
The event sequence has to be double checked and revised. I cannot find any related information in the current Vorto model. From my point of view, the upload should be part of the backup operation i.e. BACKUP_FINISHED should be reported after the upload operation. One good reason, if there is a fail in the upload, is it a successful backup?

2022-10-05 14:34 UTC, e-grigorov commented on quickstart/hono_commands_fb.py
> +    print('[stopping] demo file upload app for tenant [{}], device [{}] at [{}]'.format(tenant_id, device_id, uri))
> Wouldn't it be better if it was `file backup and restore` as this script is used for both operations?

To me it's just fine. My proposal was based on the component name but with the restore extension , it's even better.

2022-10-05 14:45 UTC, e-grigorov commented on quickstart/hono_commands_fb.py
> +            value = json.dumps(dict(correlationId=self.correlation_id, dir="./", storage="storage"))
Yes, we have to keep the how-to guide as simple as possible. That's my main concern. Actually, there was another issue with the payload, `dir` and `storage` were on the same level as corelationId but they have to be provided as options, see the Vorto model [here](https://github.com/eclipse/vorto/blob/development/models/com.bosch.iot.suite.manager.backup-BackupAndRestore-1.0.0.fbmodel/model.functionblock). In any case, they will be removed and we don't need to take care.

2022-10-06 07:25 UTC, e-grigorov commented on quickstart/hono_commands_fb.py
> +            elif body["topic"].split("/")[-1] == "modify" and body["path"].split("/")[-1] == "lastUpload":
The related ticket: eclipse-kanto/file-backup#29

2022-10-10 15:23 UTC, e-grigorov requested changes

2022-10-11 11:19 UTC, e-grigorov approved these changes

2022-10-11 15:28 UTC, konstantina-gramatova approved these changes

2022-10-12 06:26 UTC, merged