Robust download properties added to reference guide
eclipse-kanto/kanto pull request #144
Opened 2022-09-28 11:07 UTC by velitchko-valkov

[#96] Robust download properties added to reference guide 
- Added descriptions of the properties
 - Updated standard configuration

Signed-off-by: Velitchko Valkov <Velitchko.Valkov@bosch.io>

2022-09-29 09:12 UTC, e-grigorov requested changes

2022-09-29 09:12 UTC, e-grigorov commented on web/site/content/docs/references/software-update-config.md
> +| downloadRetryInterval | durationTime | 5s | Interval between retries, in case of a failed download |
dorationTime - why is it? This type is not used in the reference guide at all. All other documents just use string as a type and the description contains the special format. Could you please reuse already available descriptions?

2022-09-29 10:20 UTC, velitchko-valkov commented on web/site/content/docs/references/software-update-config.md
> +| downloadRetryInterval | durationTime | 5s | Interval between retries, in case of a failed download |
Okay, I will fix the description and type.

2022-09-30 12:39 UTC, e-grigorov requested changes

2022-09-30 12:39 UTC, e-grigorov commented on web/site/content/docs/references/software-update-config.md
> +| downloadRetryInterval | string | 5s | Interval between retries, in case of a failed download.  Should be a sequence of decimal numbers, each with optional fraction and a unit suffix, such as '300ms
All descriptions are kept short i.e. in one sentence without full stop in the end. Could you please align the format?

2022-09-30 12:49 UTC, velitchko-valkov commented on web/site/content/docs/references/software-update-config.md
> +| downloadRetryInterval | string | 5s | Interval between retries, in case of a failed download.  Should be a sequence of decimal numbers, each with optional fraction and a unit suffix, such as '300ms
Okay, I will align it.

2022-10-03 06:30 UTC, e-grigorov approved these changes

2022-10-03 06:33 UTC, merged