Provide concept guide for the Kanto Suite Connector
eclipse-kanto/kanto pull request #15
Opened 2022-06-16 11:34 UTC by antoniyatrifonova

[#11] Provide concept guide for the Kanto Suite Connector

- Provide information about what is a Suite Connector and how it works
- Provide an illustration of this concept

Signed-off-by: Antonia Trifonova Antonia.Trifonova@bosch.io

2022-06-16 13:38 UTC, e-grigorov requested changes

2022-06-16 13:38 UTC, e-grigorov commented on web/site/content/docs/concepts/_index.md
> +type: docs
Description with a single sentence is required here as it's for the getting started guide.

2022-06-16 13:38 UTC, e-grigorov commented on web/site/content/docs/concepts/suite-connector.md
> +  Enables the cloud connectivity and local communication.
- Imperative verb should be used here as it's for the getting started guide i.e. it should be: Enable...
- Suite connector doesn't enable the local communication. It's part of it. I would suggest to remove it.

2022-06-16 13:38 UTC, e-grigorov commented on web/site/content/docs/concepts/suite-connector.md
> +Suite connector enables the remote connectivity to an IoT cloud ecosystem of choice, powered by Eclipse Hono™ (e.g. [Eclipse Cloud2Edge](https://www.eclipse.org/packages/packages/cloud2edge) and Bosc
The link can be opened in a new tab. In this way, the reader will keep the focus on the concept. refn shortcode can be used. Getting started guide contains a few examples.

2022-06-16 18:10 UTC, e-grigorov requested changes

2022-06-16 18:10 UTC, e-grigorov commented on web/site/content/docs/concepts/suite-connector.md
> +Suite connector enables the remote connectivity to an IoT cloud ecosystem of choice, powered by Eclipse Hono™ (e.g. <a href="https://www.eclipse.org/packages/packages/cloud2edge" target="_blank">Ecli
My point was about refn shortcode. Here are some examples:
https://raw.githubusercontent.com/eclipse-kanto/kanto/main/web/site/content/docs/getting-started/hono.md
i.e. {{% refn "https://www.eclipse.org/packages/packages/cloud2edge" %}}Eclipse Cloud2Edge{{% /refn %}} should be used instead.

2022-06-17 07:41 UTC, e-grigorov approved these changes

2022-06-17 07:49 UTC, konstantina-gramatova approved these changes
LGTM

2022-06-17 07:51 UTC, merged