Provide How-to guide for the Kanto Local Digital Twins
eclipse-kanto/kanto pull request #155
Opened 2022-10-03 12:57 UTC by antonia-avramova

[#51] Provide How-to guide for the Kanto Local Digital Twins

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2022-10-10 11:42 UTC, e-grigorov requested changes

2022-10-10 11:42 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/local-digital-twins.md
> +  "tenantId": "demo",
Can we align the order with the example from the reference guide?

2022-10-10 11:42 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/local-digital-twins.md
> +Restart the Local Digital Twins service for the changes to take effect:
We have a second restart of the service. I guess that only one can be used.

2022-10-10 11:42 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/local-digital-twins.md
> +### Configure Local digital twins
This step sounds like a prerequisite. Just a question, what about `Before you begin` section?

2022-10-10 11:42 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/local-digital-twins.md
> +### Receive the structure of the edge device
The steps  should be as short as possible.

2022-10-10 11:42 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/local-digital-twins.md
> +Now we are ready to request the structure of the application via executing the Eclipse kanto client that requires the Local digital twins tenant (-t) and the device identifier (-d):
`structure of the application` - the document should explore the edge digital twins, not the application structure.

2022-10-10 11:42 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/local-digital-twins.md
> +A command with a similar value will be received in the terminal and status 200.
`A command with...` - it's not a command.

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +# import signal
Clean up such unused imports.

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +ditto_receive_thing_template = Template("""
`receive_thing` - I guess that it should be: `retrieve_things` or just a more generic naming as it's used by other how-to guides.

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +class MQTTClientClass(mqtt.Client):
Unusual class name.

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +        self.subscribe("command/#")
I would suggest to stick to [the Hono defined topics](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/).

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +            pub_topic = 'e/{}/{}'.format(tenant_id, device_id)
Use short or long topics, don't mix them.

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +            return rc
This  return will terminate the loop, how is rc used in the while loop?

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +# time.sleep(1)
Clean up

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +print('[starting] local-digital-twins commands app for tenant [{}], device [{}] at [{}]'.format(
Align the message with other how-to guides.

2022-10-10 11:42 UTC, e-grigorov commented on quickstart/kanto_commands_ldt.py
> +exit(0)
Signal handling is missing.

2023-12-06 09:02 UTC, k-gostev requested changes

2024-01-09 10:45 UTC, dimitar-dimitrow requested changes

2024-01-09 10:45 UTC, dimitar-dimitrow commented on quickstart/hono_commands_ldt.py
> +            rc = self.loop_stop()
I have run a dozen of times the app and even with those timeouts there is a sync issue - no retrieve-response is received as the subscription is not done on time.

2024-01-12 08:15 UTC, dimitar-dimitrow approved these changes

2024-01-16 09:00 UTC, k-gostev requested changes

2024-01-16 09:00 UTC, k-gostev commented on web/site/content/docs/how-to-guides/offline-edge-device.md
> +Stop local digital twins service and start suite connector service by executing:
```suggestion
Stop the local digital twins service and start suite connector service by executing:
```

2024-01-16 13:33 UTC, hristobojilov approved these changes

2024-01-16 14:30 UTC, hristobojilov approved these changes

2024-01-24 07:30 UTC, k-gostev approved these changes

2024-01-24 07:31 UTC, merged