Provide concept guide for the Kanto Local Digital Twins
eclipse-kanto/kanto pull request #156
Opened 2022-10-04 15:31 UTC by antonia-avramova

[#43] Provide concept guide for the Kanto Local Digital Twins

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2023-08-08 09:27 UTC, k-gostev requested changes

2023-08-08 09:27 UTC, k-gostev commented on web/site/content/docs/concepts/local-digital-twins.md
> +Local digital twins enables the digital twin state on a local level even in offline scenarios. The following use cases are provided:
```suggestion
Local digital twins enables the digital twin state on a local level even in offline scenarios. It provides the following use cases:
```

2023-08-08 09:27 UTC, k-gostev commented on web/site/content/docs/concepts/local-digital-twins.md
> +* **Synchronization** - on a connectivity recovering synchronizes the last known digital twin state
```suggestion
* **Synchronization** - when connection to the cloud is established  the last known digital twin state is synchronized
```

2023-08-08 09:27 UTC, k-gostev commented on web/site/content/docs/concepts/local-digital-twins.md
> +* **Connectivity** - provide connectivity to the cloud (similar to [Suite connector]({{< relref "suite-connector" >}}))
```suggestion
* **Cloud connectivity** - similar to [Suite connector]({{< relref "suite-connector" >}})
```

2023-08-08 09:27 UTC, k-gostev commented on web/site/content/docs/concepts/local-digital-twins.md
> +* **Provides diverse services for the applications**
```suggestion
* **Diverse services for the applications**
```

2023-08-08 09:27 UTC, k-gostev commented on web/site/content/docs/concepts/local-digital-twins.md
> +* **Provides own persistency** - digital twins are stored locally
```suggestion
* **Persistency** - digital twins are stored locally
```

2023-08-08 09:27 UTC, k-gostev commented on web/site/content/docs/concepts/local-digital-twins.md
> +### How it works
TODO @k-gostev - this whole paragraph needs rewriting

2024-06-28 07:53 UTC, dimitar-dimitrow commented on web/site/content/docs/concepts/local-digital-twins.md
> +* **Synchronization** - when connection to the cloud is established  the last known digital twin state is synchronized
```suggestion
* **Synchronization** - when connection to the cloud is established the last known digital twin state is synchronized
```

2024-06-28 07:53 UTC, dimitar-dimitrow commented on web/site/content/docs/concepts/local-digital-twins.md
> +Upon reconnection the **local digital twins** it will notifies the cloud of any changes since during the offline mode to to synchronize the digital twins state.
```suggestion
Upon reconnection, the **local digital twins** will notify the cloud of any changes during the offline mode and synchronize the digital twins state.
```

2024-06-28 08:05 UTC, merged