Add IO configuration options to the documentation
eclipse-kanto/kanto pull request #169
Opened 2022-10-18 09:28 UTC by k-gostev

This PR adds IO configuration properties to the container configuration file.
These properties are included in the API and CLI, but are missing in the documentation.
Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.io>

2022-10-19 08:28 UTC, e-grigorov requested changes

2022-10-19 08:28 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| **IO configuration**| | | |
- `IO configuration` - usually, `configuration` is missed because there is no value at all
- I would suggest to revise the order. usually, the logging is the last section

2022-10-19 08:28 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| open_stdin | bool | | Open stdin for interaction with the current container |
Just because it's a description, I would suggest to replace `stdin` with: terminal's standard input. Otherwise `STDIN` should be used because it's an abbreviation.

2022-10-19 08:28 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| tty | bool | | Attach standard streams to a TTY, including stdin if it is not closed |
`including stdin if it is not closed` - it seems that it doesn't add much more value to the first part of the description.

2022-10-24 08:12 UTC, e-grigorov requested changes

2022-10-24 08:12 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +    "io_config": {
Is it the right order? In the table above, IO is placed right after the process i.e. it should be placed after the process config.

2022-10-24 12:56 UTC, e-grigorov approved these changes

2022-10-24 13:03 UTC, konstantina-gramatova requested changes

2022-10-24 13:34 UTC, konstantina-gramatova approved these changes

2022-10-25 09:01 UTC, merged