New module with integration tests common logic #173
eclipse-kanto/kanto pull request #174
Opened 2022-11-08 12:05 UTC by hristobojilov

[#173] New module with integration tests common logic

Signed-off-by: Hristo Bozhilov <Hristo.Bozhilov@bosch.io>

2022-11-08 12:32 UTC, e-grigorov requested changes
Could you please run all tools from the validation flow.

2022-11-08 12:42 UTC, gboyvalenkov-bosch commented on integration/testutil/web.go
> +func NewWSConnection(cfg *TestConfig) (*websocket.Conn, error) {
Is it planned to add listening for ditto events?

2022-11-08 13:30 UTC, e-grigorov requested changes

2022-11-08 14:14 UTC, e-grigorov commented on integration/util/config.go
> +	StatusTimeoutMs int `env:"STATUS_TIMEOUT_MS" envDefault:"10000"`
Is it a common logic?

2022-11-08 14:15 UTC, e-grigorov commented on integration/util/config.go
> +	TimeDeltaMs int `env:"TIME_DELTA_MS" envDefault:"5000"`
Is it common logic?

2022-11-08 14:20 UTC, e-grigorov commented on integration/util/client.go
> +package testutil
Is it by mistake? Are we going to change the package name? Usually, folder name and the package name are aligned.

2022-11-08 14:21 UTC, e-grigorov commented on integration/util/client.go
> +		return ditto.ErrAcknowledgeTimeout
Is it ok to reference Ditto lib here? This method is pure MQTT.

2022-11-08 14:21 UTC, e-grigorov commented on integration/util/client.go
> +func SendMessage(cfg *TestConfig, client MQTT.Client, topic string, message interface{}) error {
We have NewMQTTClient, do we need to rename it to: SendMQTTMessage?

2022-11-08 14:25 UTC, e-grigorov commented on integration/util/suite.go
> +// Setup established connections to local broker and Ditto
- established -> establishes
- local broker -> local MQTT broker

2022-11-08 14:28 UTC, e-grigorov commented on integration/util/suite.go
> +		t.Skip(err)
I guess that TC has to fail, if environment variable can not be processed.

2022-11-08 14:32 UTC, e-grigorov commented on integration/util/web.go
> +func SendRequest(cfg *TestConfig, method string, url string) ([]byte, error) {
SendRequest sounds generic.

2022-11-08 14:36 UTC, e-grigorov commented on integration/util/web.go
> +func BeginWait(timeout time.Duration, resultCh chan error, closer func()) chan error {
BeginWait - can be call it something like: WaitError? We pass channel and return channel. Are we sure about the usage?

2022-11-08 14:37 UTC, e-grigorov commented on integration/util/web.go
> +func BeginWSWait(cfg *TestConfig, ws *websocket.Conn, check func(payload []byte) error) chan error {
The name has to be aligned with the previous function.

2022-11-08 15:55 UTC, dimiter-todorov-georgiev commented on integration/util/suite.go
> +		t.Skip(err)
Yes, please use t.FailNow. See the suite-connector integration test PR.

2022-11-08 15:57 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +func BeginWait(timeout time.Duration, resultCh chan error, closer func()) chan error {
The usage is: wait on the channel for the timeout duration. If there's no result after the given timeout, call the close function and send an error the the channel.

2022-11-09 03:52 UTC, e-grigorov commented on integration/util/web.go
> +func SendRequest(cfg *TestConfig, method string, url string) ([]byte, error) {
`SendDittoRequest` is going in the right direction. One note more, the environment variables are called `DigitalTwin...` i.e. the focus is more on the functional part. I would suggest to call this method: `SendDigitalTwinRequest`.

2022-11-09 04:00 UTC, e-grigorov commented on integration/util/web.go
> +func BeginWait(timeout time.Duration, resultCh chan error, closer func()) chan error {
@dimiter-todorov-georgiev - my confusion is that it's an error channel i.e. it waits for an error or timeout. I still cannot completely understand the flow.

2022-11-09 04:07 UTC, e-grigorov commented on integration/util/web.go
> +func BeginWSWait(cfg *TestConfig, ws *websocket.Conn, check func(payload []byte) error) chan error {
One candidate: `WaitWSMessage`

2022-11-09 08:29 UTC, e-grigorov commented on integration/util/web.go
> +				err = check(payload)
API has to be revised. Currently, payload is processed by `check` function and error channel was to be requested. It seems a little bit more complicated than it's should be just to read one message.

2022-11-09 09:57 UTC, e-grigorov commented on integration/util/client.go
> +// SendMQTTMessage sends a message to a topic using specified client
JSON Format -> JSON format

2022-11-09 11:38 UTC, hristobojilov commented on integration/util/client.go
> +		return ditto.ErrAcknowledgeTimeout
Looks ok to me

2022-11-09 12:35 UTC, e-grigorov requested changes

2022-11-09 12:35 UTC, e-grigorov commented on integration/util/web.go
> +func ProcessMessages(
ProcessWSMessages?

2022-11-09 12:35 UTC, e-grigorov commented on integration/util/web.go
> +	timeout time.Duration,
Can we have a common configuration about this? It'll be some kind of overhead for the integration tests.

2022-11-09 12:35 UTC, e-grigorov commented on integration/util/web.go
> +				fmt.Fprintf(os.Stderr, "error unmarshalling a protocol.Envelope: %v", err)
It's a test utility and cannot log on the standard error stream.

2022-11-09 12:35 UTC, e-grigorov commented on integration/util/web.go
> +	process func(*protocol.Envelope) (bool, error)) (bool, error) {
What's the reason to return this bool param? FMPOV, there is an error or not.

2022-11-09 12:35 UTC, e-grigorov commented on integration/util/web.go
> +func ProcessMessages(
Do we need this as a public method?

2022-11-09 12:35 UTC, e-grigorov commented on integration/util/web.go
> +func WaitForAck(
Do we need this as a public method?

2022-11-09 12:35 UTC, e-grigorov commented on integration/util/web.go
> +func WaitSubscribeResult(timeout time.Duration, resultCh chan SubscribeResult, closer func()) SubscribeResult {
`closer` is not used?

2022-11-09 12:35 UTC, e-grigorov commented on integration/util/web.go
> +func Subscribe(
We are in util package, revise all method names. These here should be WS specific.

2022-11-09 12:39 UTC, e-grigorov commented on integration/testutil/web.go
> +func NewWSConnection(cfg *TestConfig) (*websocket.Conn, error) {
Related API update is in progress.

2022-11-09 12:43 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +func ProcessMessages(
Yes, in case we want to process the messages synchronously.

2022-11-09 12:44 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +func WaitForAck(
Yes, we need it in some test cases.

2022-11-09 12:46 UTC, e-grigorov commented on integration/util/web.go
> +type SubscribeResult struct {
Is it really a subscribe result? As I can understand it, it's more about the cancellation of the subscription.

2022-11-09 12:46 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +	process func(*protocol.Envelope) (bool, error)) (bool, error) {
The idea is to separate "finished/stopped" from "an error has occurred".

2022-11-09 12:48 UTC, e-grigorov commented on integration/util/web.go
> +func Subscribe(
How to unsubscribe? Just to close the WS connection? Do I need a special error there?

2022-11-09 15:37 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +func BeginWait(timeout time.Duration, resultCh chan error, closer func()) chan error {
We have removed the async behavior as it wasn't required for our tests.

2022-11-10 15:37 UTC, gboyvalenkov-bosch commented on integration/util/mqtt_client.go
> +	if token := mqttClient.Subscribe("edge/thing/response", 1, func(client MQTT.Client, message MQTT.Message) {
edge/thing/response should be a constant

2022-11-10 15:37 UTC, gboyvalenkov-bosch commented on integration/util/mqtt_client.go
> +	if token := mqttClient.Publish("edge/thing/request", 1, false, ""); token.Wait() && token.Error() != nil {
use a constant for edge/thing/request

2022-11-10 15:37 UTC, gboyvalenkov-bosch commented on integration/util/suite.go
> +		require.NoError(t, err, "initialize ditto client")
just use require.Failf(...)

2022-11-10 15:37 UTC, gboyvalenkov-bosch commented on integration/util/suite.go
> +		mqttClient.Disconnect(uint(cfg.MqttQuiesceMs))
do not disconnect if connect had not been called

2022-11-10 15:37 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +	if !result.Finished {
Maybe returning only an error is sufficient in this case

2022-11-10 15:38 UTC, e-grigorov requested changes

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/mqtt_client.go
> +	timeout := time.Duration(cfg.MqttAcknowledgeTimeoutMs * int(time.Millisecond))
Is there a reason not to use the new utility method: MillisToDuration?

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/mqtt_client.go
> +		return errors.New("timeout")
The message can be more concrete. For example, `timeout while sending MQTT message`. Just discussion point, do we need to add message specific information?

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/mqtt_client.go
> +	if token := mqttClient.Publish("edge/thing/request", 1, false, ""); token.Wait() && token.Error() != nil {
This method is full with wait without timeout. Is it ok or some kind of acknowledge timeout has to be used?

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/suite.go
> +// Setup establishes connections to local MQTT broker and Ditto
`to local MQTT broker` -> `to the local MQTT broker`

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/suite.go
> +	require.NoError(t, env.Parse(cfg, opts), "Failed to process environment variables")
`Failed to` -> `failed to` - as it's for all other error messages.

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/web.go
> +func NewWSConnection(cfg *TestConfiguration) (*websocket.Conn, error) {
Just a discussion point, NewDigitalTwinWSConnection - it's more correct but it seems too long as a name. What do you think?

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/web.go
> +	return errors.New("timeout")
The message can be more concrete.

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/web.go
> +type ProcessWSMessageResult struct {
No channels, no go routines any more, it seems that this struct is not needed any more or I am missing something?

2022-11-10 15:38 UTC, e-grigorov commented on integration/util/web.go
> +func WaitForWSMessage(timeout time.Duration, ws *websocket.Conn, expectedMessage string) error {
Do we need to unify the first argument. Most of the methods are using TestConfiguration, here, timeout is used.

2022-11-10 15:45 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +type ProcessWSMessageResult struct {
It is useful for callback to _process_ func.

2022-11-11 07:33 UTC, dimiter-todorov-georgiev commented on integration/util/mqtt_client.go
> +	if token := mqttClient.Publish("edge/thing/request", 1, false, ""); token.Wait() && token.Error() != nil {
We should use `WaitTimeout(time.Duration) bool` in both places in this function.

2022-11-11 07:46 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +	if !result.Finished {
- ProcessWSMessages returns only an error
- process callback returns (bool, error)
- remove ProcessWSMessageResult

2022-11-11 07:50 UTC, e-grigorov commented on integration/util/mqtt_client.go
> +	if token := mqttClient.Subscribe("edge/thing/response", 1, func(client MQTT.Client, message MQTT.Message) {
edge/thing/response and edge/thing/request will be placed in new private constants.

2022-11-11 08:12 UTC, hristobojilov commented on integration/util/web.go
> +	return errors.New("timeout")
Any ideas here?

2022-11-11 10:27 UTC, e-grigorov commented on integration/util/config.go
> +	MqttAcknowledgeTimeoutMs int    `env:"MQTT_ACKNOWLEDGE_MS" envDefault:"3000"`
MQTT_ACKNOWLEDGE_MS -> MQTT_ACKNOWLEDGE_TIMEOUT_MS

2022-11-11 10:32 UTC, e-grigorov commented on integration/util/mqtt_client.go
> +	if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
MqttConnectMs is not used here.

2022-11-11 14:43 UTC, e-grigorov commented on integration/util/mqtt_client.go
> +	if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
Just because SetConnectTimeout is used.

2022-11-11 14:43 UTC, gboyvalenkov-bosch approved these changes

2022-11-11 15:33 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +			finished, errProcess = process(envelope)
this should be finished, err = process(envelope), and we should remove the if below. We should be able to overwrite a bad message with a good one and get a nil error if the last processed message was processed without an error.

2022-11-11 15:43 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +			finished, errProcess = process(envelope)
ОК.

2022-11-14 07:21 UTC, e-grigorov commented on NOTICE.md
> +github.com/caarlos0/env (1.7.0)
The version is not correct, it should be: v6.10.1

2022-11-14 07:23 UTC, e-grigorov commented on NOTICE.md
> +google/uuid (1.1.1)
go.mod points to version: 1.3.0

2022-11-14 10:13 UTC, e-grigorov approved these changes

2022-11-14 10:17 UTC, merged