Missing software update configuration properties
eclipse-kanto/kanto pull request #177
Opened 2022-11-16 10:17 UTC by antoniyatrifonova

[#176] Missing software update configuration properties

- provide a short description for 'installDits', 'mode', and 'serverCert' properties
- add these properties to the template

Signed-off-by: Guzgunova Antonia <Antonia.Guzgunova@bosch.io>

2022-11-16 16:03 UTC, e-grigorov requested changes

2022-11-16 16:03 UTC, e-grigorov commented on web/site/content/docs/references/software-update-config.md
> +| mode | string | strict | Restriction where the artifacts can be located, the supported modes are: strict, lax and scope |
The description should be aligned with `installDirs`. They should describe local artifacts.

2022-11-16 16:03 UTC, e-grigorov commented on web/site/content/docs/references/software-update-config.md
> +| **Download - TLS** | | | |
`Download - TLS` should be placed after the `Download` section.

2022-11-18 10:34 UTC, e-grigorov approved these changes

2022-11-18 10:42 UTC, BatGeorgi approved these changes

2022-11-18 11:56 UTC, gboyvalenkov-bosch approved these changes

2022-11-18 13:02 UTC, merged