Additional integration tests common logic
eclipse-kanto/kanto pull request #180
Opened 2022-11-18 15:38 UTC by gboyvalenkov-bosch

[#179] Additional integration tests common logic

- open for discussion
- apidoc to be completed

Signed-off-by: Georgi Boyvalenkov <Georgi.Boyvalenkov@bosch.io>

2022-11-18 15:41 UTC, hristobojilov requested changes

2022-11-18 15:41 UTC, hristobojilov commented on integration/util/web.go
> +func (suite *SuiteInitializer) ExecFeatureOperation(cfg *TestConfiguration, command string, params map[string]interface{}) error {
move this method to suite.go

2022-11-21 07:57 UTC, hristobojilov requested changes

2022-11-21 07:57 UTC, hristobojilov commented on integration/util/suite.go
> +	require.NoError(t, err, "get thing configuration")
Add defer to this line mqttClient.Disconnect(uint(cfg.MqttQuiesceMs)) because require.NoError panics and this case the client will leak.

2022-11-21 08:54 UTC, e-grigorov requested changes

2022-11-21 08:54 UTC, e-grigorov commented on integration/util/misc.go
> +// Copyright (c) 2022 Contributors to the Eclipse Foundation
misc in util :) In any case, I guess that we don't need a new file just for a single line of code. What about web.go?

2022-11-21 08:54 UTC, e-grigorov commented on integration/util/misc.go
> +// GetDigitalTwinAPIURLForThingID returns the url for executing operations on a thing
The name has to be revised, GetDigitalTwinAPI. It doesn't `get` API.

2022-11-21 08:54 UTC, e-grigorov commented on integration/util/suite.go
> +	FeatureURL string
Are we sure that stateful approach is the correct one? If there is an integration test with multiple features? If so, most probably, we have to isolate this logic to a dedicated struct.

2022-11-21 08:54 UTC, e-grigorov commented on integration/util/suite.go
> +func (suite *SuiteInitializer) ExecFeatureOperation(cfg *TestConfiguration, command string, params map[string]interface{}) error {
I guess that the operation can return something.

2022-11-21 08:54 UTC, e-grigorov commented on integration/util/suite.go
> +func (suite *SuiteInitializer) FormatURLsAndTemplates(featureID string) {
-  FormatURLsAndTemplates - the main purpose of this method is the initialization, not the formatting
- I guess that it should not be a public

2022-11-21 09:33 UTC, antoniyatrifonova requested changes

2022-11-21 09:33 UTC, antoniyatrifonova commented on integration/util/suite.go
> +	ThingURL   string
ThingID is not always the same as DeviceID. In the container management context, the ThingID is DeviceID:edge:containers

2022-11-21 09:33 UTC, antoniyatrifonova commented on integration/util/suite.go
> +}
you can use the Ditto API

2022-11-21 09:33 UTC, antoniyatrifonova commented on integration/util/suite.go
> +	namespaceID := model.NewNamespacedIDFrom(suite.ThingCfg.DeviceID)
This is not namespace ID. This is Thing ID that contains the namespace and device name

2022-11-21 09:43 UTC, gboyvalenkov-bosch commented on integration/util/suite.go
> +	FeatureURL string
That was my initial idea(using a dedicated struct), but it was discussed and we decided that it is too complex for our purposes.

2022-11-21 09:52 UTC, gboyvalenkov-bosch commented on integration/util/suite.go
> +func (suite *SuiteInitializer) FormatURLsAndTemplates(featureID string) {
It should be public, because it can optionally be called after setup, in case feature id is obtained later.

2022-11-21 11:34 UTC, hristobojilov requested changes

2022-11-21 11:34 UTC, hristobojilov commented on integration/util/suite.go
> +func (suite *SuiteInitializer) Setup(t *testing.T, featureID string) {
Is it appropriate to add second string parameter here something like thingSuffix to handle situations where the root thing is not subject for the test. We will pass empty string if the root thing is to be tested.

2022-11-21 12:36 UTC, gboyvalenkov-bosch commented on integration/util/suite.go
> +}
Too much overhead

2022-11-21 12:38 UTC, gboyvalenkov-bosch commented on integration/util/suite.go
> +func (suite *SuiteInitializer) Setup(t *testing.T, featureID string) {
Added _thingID_ parameter to _InitURLsAndTemplates_, which can be called after setup, when _deviceID_ is available.

2022-11-21 13:15 UTC, hristobojilov approved these changes

2022-11-21 13:49 UTC, e-grigorov commented on integration/util/suite.go
> +	FeatureURL string
Another option could be stateless approach.

2022-11-21 14:05 UTC, e-grigorov commented on integration/util/suite.go
> +func (suite *SuiteInitializer) FormatURLsAndTemplates(featureID string) {
In general, this reinitialization idea is very bad design idea.

2022-11-21 14:09 UTC, dimiter-todorov-georgiev approved these changes

2022-11-22 11:20 UTC, e-grigorov requested changes

2022-11-22 11:53 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +	return fmt.Sprintf(featurePropertyPathTemplate, featureID, name)
Seems like too much overhead

2022-11-22 12:04 UTC, antoniyatrifonova requested changes

2022-11-22 12:04 UTC, antoniyatrifonova commented on integration/util/web.go
> +func GetPropertyPath(featureID string, name string) string {
General note, please provide a doc

2022-11-22 12:04 UTC, antoniyatrifonova commented on integration/util/web.go
> +	return fmt.Sprintf(eventTopicTemplate, thingIDWithNamespace.Namespace, thingIDWithNamespace.Name, action)
Is it possible to use Ditto API where this is applicable?

2022-11-22 12:28 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +func GetPropertyPath(featureID string, name string) string {
Do you need a separate method?

2022-11-22 12:51 UTC, antoniyatrifonova commented on integration/util/web.go
> +func GetPropertyPath(featureID string, name string) string {
No, it's not needed

2022-11-22 13:16 UTC, antoniyatrifonova approved these changes

2022-11-22 14:26 UTC, antoniyatrifonova approved these changes

2022-11-23 07:17 UTC, e-grigorov commented on integration/util/web.go
> +	twinEventTopicTemplate      = "%s/%s/things/twin/events/%s"
Not used any more.

2022-11-23 07:17 UTC, e-grigorov commented on integration/util/web.go
> +	liveMessageTopicTemplate    = "%s/%s/things/live/messages/%s"
Not used any more.

2022-11-23 07:18 UTC, e-grigorov commented on integration/util/web.go
> +		WithCriterion(protocol.CriterionEvents).
The criterion should be: CriterionMessages.

2022-11-23 07:34 UTC, e-grigorov approved these changes

2022-11-23 07:38 UTC, merged