[#185] Added integration testing util methods for websocket connections.
eclipse-kanto/kanto pull request #186
Opened 2022-11-30 09:19 UTC by dimiter-todorov-georgiev

- UnsubscribeFromWSMessages
- Disconnect
Signed-off-by: Dimiter Georgiev <dimiter.georgiev@bosch.io>

2022-12-01 07:34 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +func UnsubscribeFromWSMessages(t *testing.T, cfg *TestConfiguration, ws *websocket.Conn, messageType string) {
Maybe we should return the error, not log it

2022-12-01 07:34 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +func logError(t *testing.T, f func() error, description string) {
I think this is not needed

2022-12-01 07:48 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +func UnsubscribeFromWSMessages(t *testing.T, cfg *TestConfiguration, ws *websocket.Conn, messageType string) {
This is so we can call this with defer:

```
	ws, err := util.NewDigitalTwinWSConnection(suite.Cfg)
	require.NoError(suite.T(), err, "cannot create a websocket connection to the backend")
	defer Disconnect(suite.T(), suite.Cfg, ws)

	filter := fmt.Sprintf("like(resource:path,'/features/%s/*')", featureID)
	err = util.SubscribeForWSMessages(suite.Cfg, ws, "START-SEND-EVENTS", filter)
	require.NoError(suite.T(), err, "subscription for events should succeed")
	defer Unsubscribe(suite.T(), suite.Cfg, ws, "STOP-SEND-EVENTS")
```

2022-12-01 07:50 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +func logError(t *testing.T, f func() error, description string) {
See my reply on the `UnsubscribeFromWSMessages` comment.

2022-12-01 08:12 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +func logError(t *testing.T, f func() error, description string) {
Okay

2022-12-01 08:26 UTC, hristobojilov requested changes

2022-12-01 08:26 UTC, hristobojilov commented on integration/util/web.go
> +func UnsubscribeFromWSMessages(t *testing.T, cfg *TestConfiguration, ws *websocket.Conn, messageType string) {
Return errors if needed, do not log them like that.

2022-12-01 08:28 UTC, hristobojilov commented on integration/util/web.go
> +func UnsubscribeFromWSMessages(t *testing.T, cfg *TestConfiguration, ws *websocket.Conn, messageType string) {
Callers may choose to ignore errors returned and defer will work even if a method returns an error.

2022-12-01 15:17 UTC, e-grigorov requested changes

2022-12-01 15:17 UTC, e-grigorov commented on integration/util/web.go
> +	if err := SubscribeForWSMessages(cfg, ws, messageType, ""); err != nil {
Unsubscribe is using `subscribe`. That's not correct at all, it seems that some more refactoring is required.

2022-12-01 15:17 UTC, e-grigorov commented on integration/util/web.go
> +		return fmt.Errorf("unable to set deadline to websocket: %v", err)
I just realized that WebSocket is written in a bunch of different ways. Could you find/replace all of them to: WebSocket?

2022-12-01 15:17 UTC, e-grigorov commented on integration/util/web.go
> +	deadline := time.Now().Add(MillisToDuration(cfg.WsEventTimeoutMs))
Hm, it seems that we somehow missed that. The configuration property should be: WSEventTimeoutMS. MQTT names have to be fixed also.

2022-12-01 15:17 UTC, e-grigorov commented on integration/util/web.go
> +			// We want this error, it shows that we've closed the connection
I am afraid that I cannot understand this comment. Could you please clarify the overall situation and how can this error help?

2022-12-01 15:49 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +func UnsubscribeFromWSMessages(cfg *TestConfiguration, ws *websocket.Conn, messageType string) error {
It has to be `from`

2022-12-01 15:56 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +		return fmt.Errorf("unable to set deadline to websocket: %v", err)
I propose this naming convention:
- In comments: `WebSocket`
- In error messages: `websocket`
- Go Package name: `websocket`
- In variable names `ws`

2022-12-01 16:02 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +func UnsubscribeFromWSMessages(cfg *TestConfiguration, ws *websocket.Conn, messageType string) error {
Done.

2022-12-01 16:03 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +// It logs any errors that occur, so that it can be called with defer.
Done.

2022-12-01 16:03 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +	if err := SubscribeForWSMessages(cfg, ws, messageType, ""); err != nil {
Done.

2022-12-01 16:03 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +		return fmt.Errorf("unable to set deadline to websocket: %v", err)
Done.

2022-12-01 16:03 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +			// We want this error, it shows that we've closed the connection
Done.

2022-12-01 16:04 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +	deadline := time.Now().Add(MillisToDuration(cfg.WsEventTimeoutMs))
I believe we missed this because `golint` and `go vet` don't complain about these.

2022-12-01 16:06 UTC, dimiter-todorov-georgiev commented on integration/util/web.go
> +	deadline := time.Now().Add(MillisToDuration(cfg.WsEventTimeoutMs))
Done.

2022-12-02 07:20 UTC, hristobojilov approved these changes

2022-12-02 07:24 UTC, e-grigorov commented on integration/util/web.go
> +// Then we wait until the connection is fully closed or the timeout expires.
`we wait` - API doc doesn't use such style. The text has to describe what the method does and there should not be: I, we etc.

2022-12-02 07:25 UTC, e-grigorov commented on integration/util/web.go
> +	// We call Close(), which sends a WebSocket close message to the backend.
`we call` - API doc doesn't use such style. The text has to describe what the method does and there should not be: I, we etc.

2022-12-02 07:31 UTC, e-grigorov commented on integration/util/web.go
> +		if err := websocket.Message.Receive(ws, &payload); err != nil {
If a concrete message is expected, it has to be asserted. Such generic error handling can be an issue.

2022-12-02 07:48 UTC, hristobojilov approved these changes

2022-12-02 08:17 UTC, e-grigorov approved these changes

2022-12-02 08:21 UTC, merged