Provide concept guide for the Kanto Container Management
eclipse-kanto/kanto pull request #19
Opened 2022-06-20 10:05 UTC by antoniyatrifonova

[#17] Provide concept guide for the Kanto Container Management

- Provide information about what is a Container Management and how it works
- Provide an illustration of this concept

Signed-off-by: Antonia Trifonova Antonia.Trifonova@bosch.io

2022-06-20 20:15 UTC, e-grigorov requested changes

2022-06-20 20:15 UTC, e-grigorov commented on web/site/content/docs/concepts/container-management.md
> +  Empower the runtime for containerized edge applications.
> Empower the runtime

I would suggest to use: Empower the edge device. The first sentence in the paragraph says: enables a lightweight standard runtime. The runtime is enabled by this features it's not empowered.

2022-06-21 08:49 UTC, e-grigorov approved these changes

2022-06-21 15:14 UTC, konstantina-gramatova requested changes

2022-06-21 15:14 UTC, konstantina-gramatova commented on web/site/content/docs/concepts/container-management.md
> +All of that is achieved on top of an underlying runtime of choice that takes care of the low-level isolation mechanisms. By default this is {{% refn "https://containerd.io/" %}}`containerd`{{% /refn
I would suggest to have the default runtime integration as a clarification in brackets rather than into a single sentence - hanging on its own. 
E.g.:

All of that is achieved on top of an underlying runtime of choice ({{% refn "https://containerd.io/" %}}`containerd`{{% /refn %}} by default) that takes care of the low-level isolation mechanisms.

The issue with the automatically added whitespaces around the shortcode rendering can be removed via adding `{{- "" -}}` before and after the `<a />` tag in [the shortcode's source](https://github.com/eclipse-kanto/kanto/blob/399d1c9b1f3fa686b6e55fb1898655481b6eab7a/web/site/layouts/shortcodes/refn.html#L2).

E.g.:
```
{{ $_hugo_config := `{ "version": 1 }` }}
{{- "" -}}<a href="{{ index .Params 0 }}" target="_blank">
            {{ if eq .Page.File.Ext "md" }}
            {{ .Inner | markdownify }}
            {{ else }}
            {{ .Inner | htmlUnescape | safeHTML }}
            {{ end }}
</a>{{- "" -}}
```

2022-06-21 22:00 UTC, konstantina-gramatova approved these changes

2022-06-22 04:21 UTC, e-grigorov approved these changes

2022-06-22 18:54 UTC, merged