Common logic for device resources
eclipse-kanto/kanto pull request #207
Opened 2023-02-28 15:06 UTC by antonia-avramova

[#206] Common logic for device resources

2023-03-02 12:23 UTC, gboyvalenkov-bosch requested changes

2023-03-02 12:23 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +	return true
return the error, not boolean

2023-03-02 12:23 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +	return true
return the error, not boolean

2023-03-02 12:23 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +	fmt.Println(string(stdout))
Consider passing _testing.T_ and logging the output

2023-03-02 12:23 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +func DeleteFile(path string) bool {
return an error, not boolean

2023-03-02 12:23 UTC, gboyvalenkov-bosch commented on integration/util/web.go
> +func createRequest(payload []byte, body interface{}, method, url, username, password string) (*http.Request, error) {
Maybe only payload parameter is enough, if you marshal the body into caller method.

2023-03-02 13:28 UTC, k-gostev commented on integration/util/registry.go
> +func DeleteResources(cfg *TestConfiguration, resources []*Resource, deviceId, url, user, pass string) bool {
I think, since those are utility functions, in general we should avoid logging errors or asserting results in them and return the proper error that should be handled by the test case that is using the utility. Also, the error returned by those functions should be descriptive enough to eliminate any need for logging, unless absolutely needed in some rare cases where debug logs could be added.

2023-03-06 12:54 UTC, gboyvalenkov-bosch requested changes

2023-03-06 12:54 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +	auth := fmt.Sprintf(authJSON, authID, password)
consider using some structure, instead of JSON formatted string and marshalling it into JSON string.

2023-03-06 12:54 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +	fileInfo, err := os.Stat(path)
return the error too or at least log it

2023-03-06 12:54 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +			devices.Devices = nil
is this line needed?

2023-03-06 12:54 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +			return err
Does this mean that some resources can remain undeleted? Maybe it is better to store the error and return it afterwise.

2023-03-09 07:33 UTC, gboyvalenkov-bosch requested changes

2023-03-09 07:33 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +	deviceJSON = `{"authorities":["auto-provisioning-enabled"]}`
Use some structure, instead of JSON formatted string.

2023-03-09 07:33 UTC, gboyvalenkov-bosch commented on integration/util/registry.go
> +	thingJSON = `{"policyId": "%s"}`
Use some structure, instead of JSON formatted string.

2023-03-10 07:24 UTC, gboyvalenkov-bosch approved these changes

2023-03-10 09:49 UTC, k-gostev requested changes

2023-03-10 09:49 UTC, k-gostev commented on integration/util/registry.go
> +}
I think it would be more readable to initialise the structures like this:

```suggestion
func CreateDeviceResources(newDeviceId, tenantID, policyID, password, registryAPI,
	registryAPIUsername, registryAPIPassword string, cfg *TestConfiguration) []*Resource {
	devicePath := tenantID + "/" + newDeviceId
	return []*Resource{
		&Resource{
			url:    registryAPI + "/devices/" + devicePath,
			method: http.MethodPost,
			body:   `{"authorities":["auto-provisioning-enabled"]}`,
			user:   registryAPIUsername,
			pass:   registryAPIPassword,
			delete: true},
		&Resource{
			url:    registryAPI + "/credentials/" + devicePath,
			method: http.MethodPut,
			body:   getCredentialsBody(strings.ReplaceAll(newDeviceId, ":", "_"), password),
			user:   registryAPIUsername,
			pass:   registryAPIPassword,
		},
		&Resource{
			url:    GetThingURL(cfg.DigitalTwinAPIAddress, newDeviceId),
			method: http.MethodPut,
			body:   fmt.Sprintf(`{"policyId": "%s"}`, policyID),
			user:   cfg.DigitalTwinAPIUsername,
			pass:   cfg.DigitalTwinAPIPassword,
			delete: true},
	}
}
```

2023-03-10 09:49 UTC, k-gostev commented on integration/util/registry.go
> +func WriteConfigFile(path string, cfg interface{}) error {
This method looks like to be more suitable for the `commons.go` as it is generic struct to file writer.

2023-03-10 09:49 UTC, k-gostev commented on integration/util/registry.go
> +	}
I think you can return if you can't find any devices, since there won't be anything to delete?

2023-03-10 09:49 UTC, k-gostev commented on integration/util/registry.go
> +	}
I think we can simplify this a bit:

```suggestion
	type registryDevice struct {
		ID  string   `json:"id"`
		Via []string `json:"via"`
	}

	type registryDevices struct {
		Devices []*registryDevice `json:"result"`
	}

	devicesJSON, err := SendDeviceRegistryRequest(nil, http.MethodGet, url, user, pass)
	if err != nil {
		return nil, err
	}
	devices := &registryDevices{}
	err = json.Unmarshal(devicesJSON, devices)
	if err != nil {
		return nil, err
	}

	var devicesVia []string
	for _, device := range devices.Devices {
		for _, via := range device.Via {
			if via == viaDeviceID {
				devicesVia = append(devicesVia, device.ID)
				break
			}
		}
	}
```

2023-03-10 09:49 UTC, k-gostev commented on integration/util/registry.go
> +	}
```suggestion
	for _, thingID := range things {
		if _, err := SendDigitalTwinRequest(cfg, http.MethodDelete, GetThingURL(cfg.DigitalTwinAPIAddress, thingID), nil); err != nil {
			deleteErrors = append(deleteErrors, err)
		}
	}
```

2023-03-10 09:49 UTC, k-gostev commented on integration/util/registry.go
> +}
This can be done with one line of code like ` exec.Command("systemctl", command, service).Output()`, so I wonder if there is need for a dedicated utility function?

2023-03-10 09:49 UTC, k-gostev commented on integration/util/web.go
> +			req.Header.Add("correlation-id", correlationID)
```suggestion
 			req.Header.Add("correlation-id",  uuid.New().String())
```

2023-03-10 09:49 UTC, k-gostev commented on integration/util/registry.go
> +func DeleteResources(cfg *TestConfiguration, resources []*Resource, deviceId, url, user, pass string) []error {
I think it would be better to return one one aggregated error describing all resources that failed to be deleted instead of `[]error`. It would be more simple to use as a utility function and would still bring the necessary error information.

2023-03-10 15:05 UTC, k-gostev commented on integration/util/registry.go
> +		}
we can simplify this a bit
```suggestion
		r := resources[i]
 		if r.delete {
 		    if _, err := SendDeviceRegistryRequest(nil, http.MethodDelete, r.url, r.user, r.pass); err != nil {
 			    errStrings = append(errStrings, err.Error())
 		    }
 	       }
 ```

2023-03-13 14:09 UTC, k-gostev approved these changes

2023-03-13 14:13 UTC, k-gostev requested changes
golint reports:
```
registry.go:22:6: exported type Resource should have comment or be unexported
registry.go:34:6: exported type BootstrapConfiguration should have comment or be unexported
registry.go:46:6: exported type ConnectorConfiguration should have comment or be unexported
registry.go:57:28: func parameter newDeviceId should be newDeviceID
registry.go:92:3: struct field AuthId should be AuthID
registry.go:102:69: func parameter deviceId should be deviceID
```
Please fix it.

2023-03-14 08:47 UTC, k-gostev approved these changes

2023-03-15 09:13 UTC, gboyvalenkov-bosch approved these changes

2023-03-15 09:55 UTC, merged