Pick up the latest integration util changes into c2e-setup
eclipse-kanto/kanto pull request #211
Opened 2023-03-20 11:46 UTC by antonia-avramova

[#208] Pick up the latest integration util changes into c2e-setup

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2023-03-21 09:50 UTC, gboyvalenkov-bosch requested changes

2023-03-21 09:50 UTC, gboyvalenkov-bosch commented on integration/c2e-setup/main.go
> +		fmt.Printf("error restarting %s: %v", service, err)
Maybe print the output, too. Can it be non-empty, even if there is an error?

2023-03-21 09:50 UTC, gboyvalenkov-bosch commented on integration/c2e-setup/main.go
> +	ldt = *flag.Bool("ldt", false, "Create local-digital-twins resources")
Maybe add validation of flags, i.e check if bootstrap and ldt are both enabled.

2023-03-21 09:50 UTC, gboyvalenkov-bosch commented on integration/c2e-setup/main.go
> +func deleteBackupFile(path string) bool {
use something more generic, like deleteFile?

2023-03-21 09:50 UTC, gboyvalenkov-bosch commented on integration/c2e-setup/main.go
> +func performSetUp(deviceId string, resources []*util.Resource) bool {
rename deviceId to deviceID, check with golint

2023-03-22 07:51 UTC, gboyvalenkov-bosch approved these changes

2023-03-23 12:23 UTC, antoniyatrifonova approved these changes

2023-03-23 15:26 UTC, dimitar-dimitrow approved these changes

2023-03-23 15:29 UTC, merged