Prepare concept documentation page for the Update Manager
eclipse-kanto/kanto pull request #240
Opened 2023-06-15 13:54 UTC by philip-fidanov

2023-07-05 09:00 UTC, k-gostev requested changes
In web/site/static/images/docs/concepts/update-manager.png the cloud section should be identical with the other concepts and should include Hono, Ditto, Bosch IoT Suite, Microsoft Azure, even though those are subject to future development.

Also, please check the sides of the big rectangle, it seems to me that the right side is smaller than the left

2023-07-26 11:30 UTC, k-gostev approved these changes

2023-08-29 04:30 UTC, dimitar-dimitrow approved these changes

2023-09-01 06:56 UTC, hristobojilov approved these changes

2023-09-01 06:57 UTC, merged