Prepare documentation page for the Update Manager configuration
eclipse-kanto/kanto pull request #248
Opened 2023-06-26 09:11 UTC by philip-fidanov

[#242] Prepare documentation page for the Update Manager configuration

Signed-off-by: Filip Fidanov [Filip.Fidanov@bosch.io](mailto:Filip.Fidanov@bosch.io)

2023-06-26 09:56 UTC, k-gostev requested changes
I don't think we need additional directory just for the update manager, @hristobojilov, @dimitar-dimitrow wdyt?

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| **Domain agent** | | | |
I guess it should match the json template.
```suggestion
| **Domain agents** | | | |
```

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| rebootRequired | bool | false | Specify the reboot required flag for the given domain |
`name` is missing, but is listed in the json template

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| phaseTimeout | string | 10m | Specify the timeout for completing an Update Orchestration phase |
```suggestion
| phaseTimeout | string | 10m | Timeout as duration string for completing an Update Orchestration phase |
```

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| domain | string | device | Specify the Domain of this update agent, used as MQTT topic prefix |
```suggestion
| domain | string | device | The domain of this update agent, used as MQTT topic prefix |
```

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| domains | string | containers,self-update,safety-domain| Specify a comma-separated list of domains handled by the update manager |
```suggestion
| domains | string | containers,self-update,safety-domain| A comma-separated list of domains handled by the update manager |

```

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| rebootAfter | string | 30s | Specify the timeout in cron format to wait before a reboot process is initiated after successful update operation |
```suggestion
| rebootAfter | string | 30s | Time period in cron format to wait before a reboot process is initiated after successful update operation |

```

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| rebootEnabled | bool | true | Specify a flag that controls the enabling/disabling of the reboot process after successful update operation |
```suggestion
| rebootEnabled | bool | true | Enable the reboot process after successful update operation |
```

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| reportFeedbackInterval | string | 1m | Specify the time interval for reporting intermediate desired state feedback messages during an active update operation |
```suggestion
| reportFeedbackInterval | string | 1m | Time interval as duration string for reporting intermediate desired state feedback messages during an active update operation |
```

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| currentStateDelay | string | 30s | Specify the time delay for reporting current state messages |
Adapt all other time properties in a similar way

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| rebootRequired | bool | false | Specify the reboot required flag for the given domain |
```suggestion
| rebootRequired | bool | false | Require a reboot for the given domain |
```

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| **Local connectivity** | | | |
Please check the `Digital Twin - connectivity` section [here](https://eclipse.dev/kanto/docs/references/containers/container-manager-config/) and copy the descriptions from there.

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +| **Logging** | | | |
Please check the `Logging` section [here](https://eclipse.dev/kanto/docs/references/containers/container-manager-config/) and copy the descriptions from there.

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +### Template
Example section is missing, please check the other similar reference docs and add one.

2023-06-26 09:56 UTC, k-gostev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +	"mqtt": {
IMO `mqtt` should be `connection`,  `local_connection`, `connectivity` or `local_connectivity` or something similar. @stoyan-zoubev could you fix it in the update-manager, please? Sorry, I have missed that

2023-06-26 12:14 UTC, philip-fidanov commented
> I don't think we need additional directory just for the update manager, @hristobojilov, @dimitar-dimitrow wdyt?

Тhe purpose for defining a separate directory for the update manger is to hold both the update manager configuration and APIs, which will be published further in a separate PR. And the index file is common.

2023-06-26 12:44 UTC, stoyan-zoubev commented on web/site/content/docs/references/updatemanager/update-manager-config.md
> +	"mqtt": {
Yes, we shall align the configuration properties for local connectivity with the other Kanto components.

2023-06-26 13:18 UTC, dimitar-dimitrow commented
@philip-fidanov as currently only configurations are available in the references guide lets keep it that way. The APIs could be published in the Update Manager repository for now.

2023-07-03 09:55 UTC, dimitar-dimitrow requested changes

2023-07-03 09:55 UTC, dimitar-dimitrow commented on web/site/content/docs/references/update-manager-config.md
> +| rebootAfter | string | 30s | Time period in cron format to wait before a reboot process is initiated after successful update operation |
The cron format is used for specifying the scheduling of tasks, rather than representing time periods or durations. Cron expressions are used to define the timing of recurring tasks based on specific time points, not durations.

2023-07-03 09:55 UTC, dimitar-dimitrow commented on web/site/content/docs/references/update-manager-config.md
> +	"domains": "containers,self-update",
Could we skip or substitute the _self-update_ domain, as it is not kanto specific? Either skip it all or use a name that obviously represents a fictional/custom domain name.

2023-07-31 06:05 UTC, k-gostev approved these changes

2023-08-24 09:56 UTC, dimitar-dimitrow requested changes

2023-08-24 09:56 UTC, dimitar-dimitrow commented on web/site/content/docs/references/update-manager-config.md
> +| name | string | | Domain name |
```suggestion
| name | string | | Domain name |
```
check - https://github.com/eclipse-kanto/update-manager/issues/38

2023-08-24 09:56 UTC, dimitar-dimitrow commented on web/site/content/docs/references/update-manager-config.md
> +			"name": "containers",
```suggestion
		"containers": {
```
check - https://github.com/eclipse-kanto/update-manager/issues/38

2023-08-29 04:36 UTC, dimitar-dimitrow approved these changes

2023-08-30 14:44 UTC, closed without merging

2023-08-30 14:44 UTC, dimitar-dimitrow commented
Replaced by: #269