Prepare documentation page for the Containers Component configuration
eclipse-kanto/kanto pull request #270
Opened 2023-09-01 06:43 UTC by k-gostev

[#243] Prepare documentation page for the Containers Component configuration

2023-09-04 08:15 UTC, hristobojilov requested changes

2023-09-04 08:15 UTC, hristobojilov commented on web/site/content/docs/references/containers/container-component-config.md
> +| restartPolicy | string | unless-stopped | The container's restart policy, the supported values are: `always` - an attempt to restart the container will be me made each time the container exits rega
will be me made-> will be made

2023-09-04 08:15 UTC, hristobojilov commented on web/site/content/docs/references/containers/container-component-config.md
> +| memorySwap | No | | Sets the total amount of memory + swap that the container can use in the form of 200m, 1.2g. If set must not be smaller than `memory`. If equal to `memory`, than the container w
Likely than must be replaced by then

2023-09-21 07:33 UTC, hristobojilov approved these changes

2023-09-21 08:47 UTC, dimitar-dimitrow approved these changes

2023-09-28 07:21 UTC, merged