Initial contribution of the AWS Connector Guides.
eclipse-kanto/kanto pull request #285
Opened 2023-10-05 13:18 UTC by yonko-gospodinov

2023-10-06 08:34 UTC, hristobojilov requested changes

2023-10-06 13:51 UTC, k-gostev requested changes

2023-10-06 13:51 UTC, k-gostev commented on web/site/content/docs/references/connectivity/aws-connector-config.md
> +---
Please add example with minimum working configuration similar to the other modules

2023-10-10 07:31 UTC, k-gostev approved these changes

2023-10-10 07:32 UTC, hristobojilov approved these changes

2023-10-10 08:09 UTC, merged