Provide how to guide for verifying signed container images
eclipse-kanto/kanto pull request #309
Opened 2024-01-05 15:54 UTC by dimitar-dimitrow

[#307] Provide how to guide for verifying signed container images

Signed-off-by: Dimitar Dimitrov <dimitar.dimitrov3@bosch.com>

2024-01-16 09:38 UTC, k-gostev requested changes

2024-01-16 09:38 UTC, k-gostev commented on web/site/content/docs/how-to-guides/verify-signed-container-images.md
> +By following the steps below you will sign a container image and push it to a local registry using a{{% refn "https://github.com/notaryproject/notation" %}}`notation`{{% /refn %}}. Then notation trus
```suggestion
By following the steps below, you will sign a container image and push it to a local registry using a{{% refn "https://github.com/notaryproject/notation" %}}`notation`{{% /refn %}}. Then a notation trust policy and the Kanto Container Management service will be configured in a way that running containers from the signed image via kanto-cm CLI will be successful, while running containers from unsigned images will fail. 
```

2024-01-16 09:38 UTC, k-gostev commented on web/site/content/docs/how-to-guides/verify-signed-container-images.md
> +Generate a key-pair with notation and add it as the default key to be used by notation when signing:
```suggestion
Generate a key-pair with notation and add it as the default signing key:
```

2024-01-16 09:38 UTC, k-gostev commented on web/site/content/docs/how-to-guides/verify-signed-container-images.md
> +Configure the use of notation verifier, set it's config directory and also mark the local registry as a insecure one:
```suggestion
 Configure the use of notation verifier, set its config directory, and mark the local registry as an insecure one:
```

2024-01-16 09:38 UTC, k-gostev commented on web/site/content/docs/how-to-guides/verify-signed-container-images.md
> +Create and run container from the signed image. The container prints `Hello world` to the console:
```suggestion
Create and run a container from the signed image. The container prints `Hello world` to the console:
```

2024-01-16 09:38 UTC, k-gostev commented on web/site/content/docs/how-to-guides/verify-signed-container-images.md
> +Make sure that docker hub hello_world image is not cached localy and verify that creating containers from it fails, as the image is not signed and the signature verification fails:
```suggestion
Make sure that a docker hub hello_world image is not cached locally and verify that creating containers from it fails, as the image is not signed, and the signature verification fails: 
```

2024-01-16 09:38 UTC, k-gostev commented on web/site/content/docs/how-to-guides/verify-signed-container-images.md
> +Remove the created container from Kanto Container Management and the localy cached image:
```suggestion
Remove the created container from the Kanto Container Management and the locally cached image: 
```

2024-01-16 09:38 UTC, k-gostev commented on web/site/content/docs/how-to-guides/verify-signed-container-images.md
> +```shell
hmm, we should add an option in the kanto-cm CLI to remove the image as well

2024-01-17 06:02 UTC, dimitar-dimitrow commented on web/site/content/docs/how-to-guides/verify-signed-container-images.md
> +```shell
By configuring the _image_expiry_ to 0s, the locally cached images will be deleted automatically when no containers are using them.

2024-01-24 07:35 UTC, k-gostev approved these changes

2024-01-24 07:35 UTC, merged