Switch to hugo modules
eclipse-kanto/kanto pull request #319
Opened 2024-03-01 09:08 UTC by antonia-avramova

Switch to hugo modules

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2024-04-09 13:33 UTC, dimitar-dimitrow requested changes
This [readme](https://github.com/eclipse-kanto/kanto/blob/main/web/README.md) should also be updated according to other changes from this PR:
- the sub-module step seems unnecessary, as we switch to Hugo modules
- the minimal Hugo version should be updated
- the link for installing Hugo may be updated
- kanto logo link is wrong

2024-04-09 13:33 UTC, dimitar-dimitrow commented on web/site/go.mod
> +go 1.22.0
Could we use go 1.21 be used as a minimal version? If there is no explicit dependency for 1.22, we better keep 
 to the older version, as 1.21 is the most used version for builds across kanto repositories.

2024-04-09 13:33 UTC, dimitar-dimitrow commented on web/site/content/docs/references/containers/api-reference/_index.md
> +title: "API Reference"
This `API Reference` would fit better in a separate PR. @k-gostev what do you think?

2024-04-09 13:34 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/_index.md
> +title: "API Reference"
Absolutely, this commit was due to some tests that I made, so it should be dropped

2024-04-09 13:40 UTC, dimitar-dimitrow commented
@k-gostev, @antonia-avramova  Do we need to update the Hugo version in the [documentation](https://github.com/eclipse-kanto/kanto/blob/main/.github/workflows/documentation.yaml) workflow as well?

2024-04-11 08:10 UTC, dimitar-dimitrow approved these changes

2024-04-11 11:07 UTC, merged