[#278] Expand documentation with API definitions, message formats and other technical details.
eclipse-kanto/kanto pull request #325
Opened 2024-04-25 09:09 UTC by antonia-avramova

[#278] Expand documentation with API definitions, message formats and other technical details.

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2024-04-30 07:13 UTC, k-gostev requested changes

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +Install given list of software modules to the container.
```suggestion
You can install a specified list of containers (software modules).
```

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +> | softwareModules | - | Array from modules, which will be installed |
```suggestion
> | softwareModules | - | An array of modules that will be installed. |
```

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +**Example** : In this example, the User can install listed modules:
```suggestion
**Example** : In this example, you can install the listed modules.
```

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +> | softwareModules | - | Array from modules, which will be installed |
you should describe the software module structure and what parameters it takes, references to the hawk bit APIs would also be helpful

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +  <summary>Response</summary>
the response should follow the format of the request

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +Remove software modules from the container.
```suggestion
Remove a software module that is already installed.
```

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +> | value | - | Json presentation of software module to be removed |
all parameters of the value should be described

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +  <summary>Response</summary>
the request should follow the format of the response

2024-04-30 07:13 UTC, k-gostev commented on web/site/content/docs/references/file-backup/file-backup.md
> +  The file backup service provides the ability to backup and restore to and from a backend storage.
```suggestion
The file backup service allows you to backup and restore data to and from a backend storage.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : In this example, you can pause an existing and running container.
This line seems to be copied from CM, fix it accordingly to the FU.

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +Cancel upload the file.
```suggestion
Cancel a file upload.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : In this example, you can resume cancel operation upload of the file.
```suggestion
**Example** : In this example, you can cancel a file upload.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : The response of the cancel upload file operation.
```suggestion
**Example** : The response of the cancel file upload operation.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +Activate upload of the file.
```suggestion
Activate a file upload.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : The response of the start upload file operation.
```suggestion
**Example** : The response of the start file upload operation.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +Start to upload file.
```suggestion
Start a file upload.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +Trigger operation is invoked from the backend.
All operations are invoked by the backend., align with the other descriptions.

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : In this example, you can activate upload of the file.
```suggestion
**Example** : In this example, you can activate a file upload.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : In this example, you can deactivate upload of file.
```suggestion
**Example** : In this example, you can deactivate a file upload.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +Deactivate upload file.
```suggestion
Deactivate a file upload.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : In this example, you can start uploading a file.
```suggestion
**Example** : In this example, you can start a file upload.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : The response of the activate upload file operation.
```suggestion
**Example** : The response of the activate file upload operation.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/file-upload/file-upload-api.md
> +**Example** : The response of the deactivate upload file operation.
```suggestion
**Example** : The response of the deactivate file upload operation.
```

2024-06-27 07:58 UTC, dimitar-dimitrow commented on web/site/content/docs/references/local-digital-twins/local-digital-twins-config.md
@k-gostev do we need to move the ldt reference guide in a sub-folder?

2024-06-27 08:38 UTC, k-gostev commented on web/site/content/docs/references/local-digital-twins/local-digital-twins-config.md
we can move it in the connectivity folder

2024-06-27 15:37 UTC, dimitar-dimitrow commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
> +	"topic":"edge/device/things:edge:containers/live/messages/remove",
```suggestion
	"topic":"edge/device:edge:containers/things/live/messages/remove",
```

2024-06-27 15:37 UTC, dimitar-dimitrow commented on web/site/content/docs/references/containers/api-reference/software-updatable.md
>  **Topic:** `command//edge:device/res//install``
```suggestion
**Topic:** `command//edge:device:edge:containers/res//install``
```

2024-06-27 15:37 UTC, dimitar-dimitrow commented on web/site/content/docs/references/containers/api-reference/container.md
>  **Topic:** `command//edge:device/res//stopWithOptions``
```suggestion
**Topic:** `command//edge:device:ege:containers/res//stopWithOptions``
```

2024-06-28 06:36 UTC, dimitar-dimitrow approved these changes

2024-06-28 06:38 UTC, merged