Build Yocto Image for Raspberry Pi with Kanto recepies
eclipse-kanto/kanto pull request #351
Opened 2024-10-25 12:55 UTC by sanjeev-joshi

Document describing how to create yocto image for raspberry pi with kanto recepies has been prepared

2024-10-30 07:15 UTC, hristobojilov requested changes

2024-10-30 07:15 UTC, hristobojilov commented on web/site/content/docs/how-to-guides/build-yocto-image-raspberry-pi.md
> +  bitbake-layers add-layer /home/path/to/meta/layer/directory
Please add more detailed description which layers exactly need to be added. There are quite many in meta-openembedded git repo. The's one layer missing as well i.e. meta-lts-mixins and it's not possible to build most kanto modules without it. See here https://github.com/eclipse-kanto/meta-kanto/blob/kirkstone/.github/workflows/validation.yml

2024-10-30 07:15 UTC, hristobojilov commented on web/site/content/docs/how-to-guides/build-yocto-image-raspberry-pi.md
> +* After the successful build, the image will be availabe at the below location.
It would be very useful if it's possible to test the build with qemu without having raspberry PI available. It's very nice if instructions how to do so are added as well.

2024-10-30 12:38 UTC, sanjeev-joshi commented on web/site/content/docs/how-to-guides/build-yocto-image-raspberry-pi.md
> +* After the successful build, the image will be availabe at the below location.
Added instructions on how to test the build with qemu

2024-10-30 12:38 UTC, sanjeev-joshi commented on web/site/content/docs/how-to-guides/build-yocto-image-raspberry-pi.md
> +  bitbake-layers add-layer /home/path/to/meta/layer/directory
Provided a detailed description of what all layers needs to be added.

2024-11-04 09:03 UTC, sanjeev-joshi commented
[yocto_build_qemuarm.log](https://github.com/user-attachments/files/17615885/yocto_build_qemuarm.log)
[yocto_raspberrypi4-64.log](https://github.com/user-attachments/files/17615887/yocto_raspberrypi4-64.log)


Yocto build logs for qemuarm and for raspberrypi machine has been attached.

2024-11-04 09:05 UTC, sanjeev-joshi commented
[bblayers.txt](https://github.com/user-attachments/files/17615895/bblayers.txt)
[local.txt](https://github.com/user-attachments/files/17615896/local.txt)

bblayer and local.conf have been attached in text format.

2024-11-04 09:07 UTC, sanjeev-joshi commented
[Build_Logs_Screenshots.zip](https://github.com/user-attachments/files/17615906/Build_Logs_Screenshots.zip)

Screenshots of Build logs and test with qemuarm have been attached.

2024-11-04 09:55 UTC, sanjeev-joshi commented
[yocto_build_log_qemuarm64.log](https://github.com/user-attachments/files/17616386/yocto_build_log_qemuarm64.log)

Attached the yocto build log for qemuarm64 machine for reference.

2024-11-04 09:57 UTC, sanjeev-joshi commented
Screenshots for running qemuarm64 image and verify kanto components have been attached.
[qemuarm64_screenshots.zip](https://github.com/user-attachments/files/17616407/qemuarm64_screenshots.zip)

2024-11-04 12:20 UTC, hristobojilov approved these changes

2024-11-05 06:24 UTC, merged