Provide Reference guide for the Kanto Container Management
eclipse-kanto/kanto pull request #58
Opened 2022-07-11 16:28 UTC by antoniyatrifonova

[#40 ] Provide Reference guide for the Kanto Container Management

- provide the information relevant to available configuration per container instance
- add an example how to use this configuration
- add a refrence guide for container instance configuration in Eclipse Kanto Documentation

Signed-off-by: Trifonova Antonia <Antonia.Trifonova@bosch.io>

2022-07-12 05:43 UTC, e-grigorov commented
PR title can be adjusted to be more concrete. It's all about the configuration of the container instance.

2022-07-12 11:31 UTC, e-grigorov requested changes

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +### Template
The property order of the template should be the same as it's in the table above.

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +### Properties
TOC is missing.

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| **Host config** | | | |
There are 3-4 "config" categories. This page is all about configuration, all categories have to be revised and the configuration should be removed in the end. The category should answer to the question: what is it for? For example: logging, local connectivity etc.

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| **Encrypted images** | | | |
This category can be simplified to: Encryption i.e. what is it for. All other categories can be revised.

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| name | string | | The full name of the container image |
Is it enough to say full name? Do we need to say something about the schema as it was done for the broker property of the software update. In the end this full name can contain: registry, image name, tag etc.

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| **Container config** | | | |
"Container config" - fully overlaps with the title. It's clear that it's based on the JSON key but the idea has to be revised.

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| **Driver config** | | | |
Driver config but is the context of the logging.

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| root_dir | string | *Default container-management's meta path* | The target directory to store the logs per container. A sub-directory is created for each container’s ID. This is applicable for jso
The default value is more like a description.

2022-07-12 11:31 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| max_size | string | 100M | The max size of the logs. This is applicable for json-file log driver only. |
For all these string representations, it should be useful to have the format. In this way, it'll be clear which are supported units.

2022-07-29 12:56 UTC, e-grigorov requested changes

2022-07-29 12:56 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| **Image - encryption** | | | |
Actually, it should be: Image - decryption

2022-07-29 12:56 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| host_port | int | | Host ports beginning range |
It sounds like the beginning rage of the host ports but it should be: beginning of the host ports range.
The same is valid for the end.

2022-07-29 12:56 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| destination | string | | Path to the file or directory is mounted inside the container |
"...directory is mounted" should be: ...directory that is mounted

2022-07-29 12:56 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| max_size | string | 100M | Maximum logs size before getting rotated as a number with a unit suffix of B, K, M and G |
"Maximum logs" has to be: Maximum log file size
for a reference, see: https://websites.eclipseprojects.io/kanto/docs/references/suite-connector-config/

2022-08-01 10:47 UTC, e-grigorov requested changes

2022-08-01 10:47 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| retry_timeout | int | 100 | Timeout period for each retry that is made to restart the container on exit |
Unit of measurement has to be added.

2022-08-01 10:47 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| memory_swap | string | | Total amount of memory and swap that the container can use as a number with a unit suffix of B, K, M and G, use -1 to allow the container to use unlimited swap |
"memory and swap" - is it memory and swap or only the swap?

2022-08-01 11:40 UTC, antoniyatrifonova commented on web/site/content/docs/references/containers/container-config.md
> +| memory_swap | string | | Total amount of memory and swap that the container can use as a number with a unit suffix of B, K, M and G, use -1 to allow the container to use unlimited swap |
This is total memory limit - memory + swap.

2022-08-02 08:07 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-config.md
> +| retry_timeout | int | 100 | Timeout period for each retry that is made to restart the container on exit |
With the last fix where we have the unit of measurement, the default values are removed and the default behavior is unclear.

2022-08-02 12:57 UTC, e-grigorov approved these changes

2022-08-02 15:37 UTC, konstantina-gramatova requested changes
Please decide on a common wording regarding the properties descriptions:
Use only `a container` or `the container` when referring to the actual instance being configured.
Apply it in all descriptions consistently.

2022-08-02 15:37 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +  Customize the deployment of container instance.
of a container instance

2022-08-02 15:37 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +| propagation_mode | string | rprivate | Propagation mode in which mounts in container are accessible on host, the supported modes are: rprivate, private, rshared, shared, rslave or slave |
Can we simplify, e.g.:

Bind propagation for the mount, supported are: rprivate, private, rshared, shared, rslave or slave

2022-08-02 15:37 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +| mode | string | blocking | Messaging delivery mode from the container to log driver, the supported modes are: blocking and non-blocking |
..... to the log driver

2022-08-04 09:17 UTC, konstantina-gramatova requested changes

2022-08-04 09:17 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +| max_buffer_size | string | 1M | Maximum buffer size to store the messages per container as a number with a unit suffix of B, K, M and G |
* `per container` maybe should be `for the container`?
* Could you check whether this configuration applies per container or is a general one for a shared driver?

2022-08-04 10:02 UTC, antoniyatrifonova commented on web/site/content/docs/references/containers/container-config.md
> +| max_buffer_size | string | 1M | Maximum buffer size to store the messages per container as a number with a unit suffix of B, K, M and G |
This configuration applies for the container.

2022-08-05 07:25 UTC, konstantina-gramatova requested changes

2022-08-05 07:25 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +| root_dir | string | <meta_path>/containers/<container_id> | Root directory where the log messages are stored per the container |
Simplify, e.g.:

.... where the container's log messages are stored

2022-08-05 07:25 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +| type | string | unless-stopped | The container restart policy, the supported types are: always, no, on-failure and unless-stopped |
The container **'s** restart policy .....

2022-08-05 07:25 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +| max_buffer_size | string | 1M | Maximum buffer size to store the messages for the container as a number with a unit suffix of B, K, M and G |
Maximum size of the buffered container's log messages in a non-blocking mode as a number  ......

2022-08-05 07:25 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +The minimal required information to create the container instance is the receptive container image.
to create a container instance...



// Here we aim a generic minimal configuration with a simple useful scenario. Thus, we use `a` instead of `the`.

2022-08-05 07:25 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +Be aware that some combinations require property removal.
may require?

2022-08-05 08:33 UTC, konstantina-gramatova requested changes

2022-08-05 08:33 UTC, konstantina-gramatova commented on web/site/content/docs/references/containers/container-config.md
> +The minimal required information to create a container instance is the receptive container image.
Te whole sentence lacks semantics.....

Shouldn't it be something like:

The minimal required configuration to spin up an InfluxDB container instance.

2022-08-08 08:58 UTC, konstantina-gramatova approved these changes

2022-08-08 09:00 UTC, merged