Provide How-to guide for installing a Debian package via Software Update
eclipse-kanto/kanto pull request #65
Opened 2022-07-25 11:02 UTC by gabriela-yoncheva

[#12] Provide How-to guide for Software Update

- created an application that spins up a hello Debian package at the edge
- added a guide to the Eclipse Kanto Documentation
- updated Software Update concept page with link to the how to guide
- created bash script for installing hello Debian package

Signed-off-by: Gabriela Yoncheva <Gabriela.Yoncheva@bosch.io>

2022-07-26 07:11 UTC, e-grigorov requested changes

2022-07-26 07:11 UTC, e-grigorov commented on quickstart/hono_commands_su.py
> +              "SHA1": "$sha1"
SHA256 should be a better option.

2022-07-26 07:11 UTC, e-grigorov commented on quickstart/hono_commands_su.py
> +        "correlationId": "$correlation_id"
I would suggest to format the template as typical JSON. correlationId is on the same level as softwareModules.

2022-07-26 07:11 UTC, e-grigorov commented on web/site/content/docs/getting-started/hono.md
> +  wget https://github.com/eclipse-kanto/kanto/raw/main/quickstart/hono_update_software.py && \
The script is called: hono_comments_su.py and should be downloaded in the related how-to guide document.

2022-07-26 07:11 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/update-software.md
> +python3 hono_update_software.py -t demo -d demo:device
The file name is not up to date.

2022-07-29 14:21 UTC, e-grigorov requested changes

2022-07-29 14:21 UTC, e-grigorov commented on quickstart/hono_commands_su.py
> +ditto_live_inbox_msg_template = Template("""
As we have a dedicated software update script, we don't need this generic template. Both templates can be merged and it'll remove a lot of inlined strings.

2022-07-29 14:21 UTC, e-grigorov commented on quickstart/hono_commands_su.py
> +        action = "install"
As it's a fixed value, it can be inlined in the template.

2022-07-29 14:21 UTC, e-grigorov commented on quickstart/hono_commands_su.py
> +        feature = "SoftwareUpdatable"
As it's a fixed value, it can be inlined in the template.

2022-07-29 14:21 UTC, e-grigorov commented on quickstart/hono_commands_su.py
> +            module_name="hello", version="2.10", size=30,
All fixed values can be inlined in the template.

2022-07-29 14:21 UTC, e-grigorov commented on quickstart/hono_commands_su.py
> +            url="https://github.com/eclipse-kanto/kanto/raw/main/quickstart/install_hello.sh",
* I would suggest to use "install-hello" for the module name as this module is about the install script.
* If the module is about the install script, the version can be: 1.0.0

2022-07-29 14:21 UTC, e-grigorov commented on quickstart/hono_commands_su.py
> +
Redundant new line.

2022-08-02 08:10 UTC, e-grigorov requested changes

2022-08-02 08:10 UTC, e-grigorov commented on web/site/content/docs/how-to-guides/update-software.md
> +* If you don't have an installed and running Eclipse Kanto, follow {{% relrefn "hono" %}} Install Eclipse Kanto {{% /relrefn %}}
The link should point to the Kanto installation, not explore via Hono.

2022-08-02 15:43 UTC, konstantina-gramatova approved these changes

2022-08-03 07:29 UTC, merged