Provide How-to guide for uploading a log file to a simple HTTP server
eclipse-kanto/kanto pull request #66
Opened 2022-07-25 13:18 UTC by ognian-baruh

[#13] Provide How-to guide for File Upload

- created a Python script that uploads a log file to a simple HTTP server
- created a guide in the Eclipse Kanto Documentation
- updated File Upload Concept page with a link to the File Upload How-to guide

Signed-off-by: Ognian Baruh <Ognyan.Baruh@bosch.io>

2022-07-26 07:21 UTC, e-grigorov requested changes

2022-07-31 21:05 UTC, e-grigorov requested changes

2022-07-31 21:05 UTC, e-grigorov commented on quickstart/hono_commands_fu.py
> +        upload_options = {"https.url": "http://localhost:8080/suite-connector.log"}
In this way, the trigger command will have these options but it doesn't have to. Only the start command should have them.

2022-08-01 13:52 UTC, e-grigorov requested changes

2022-08-01 13:52 UTC, e-grigorov commented on quickstart/hono_commands_fu.py
> +                os.kill(os.getpid(), signal.SIGINT)
It's too early to do os.kill here. It should be done on the last status report event.

2022-08-04 08:18 UTC, e-grigorov requested changes

2022-08-04 08:18 UTC, e-grigorov commented on quickstart/hono_commands_fu.py
> +                    if body["value"]["state"] == "SUCCESS":
The app should stop on any final state: https://github.com/eclipse/vorto/blob/development/models/com.bosch.iot.suite.manager.upload-State-1.0.0.type/model.datatype
i.e. SUCCESS, FAILED, CANCELED

2022-08-04 10:52 UTC, e-grigorov approved these changes

2022-08-05 07:33 UTC, konstantina-gramatova approved these changes

2022-08-05 08:03 UTC, merged