Provide Reference guide for the Kanto System Metrics
eclipse-kanto/kanto pull request #84
Opened 2022-08-11 07:00 UTC by gboyvalenkov-bosch

[#49] Provide Reference guide for the Kanto System Metrics

- reference guide created

Signed-off-by: Georgi Boyvalenkov <Georgi.Boyvalenkov@bosch.io>

2022-08-11 11:53 UTC, e-grigorov requested changes

2022-08-11 11:53 UTC, e-grigorov commented on web/site/content/docs/references/system-metrics-config.md
> +  Customize the system metrics.
Here, we have a focus on the most important functionality, not on the component name. Look around and check the rest of the descriptions.

2022-08-11 11:53 UTC, e-grigorov commented on web/site/content/docs/references/system-metrics-config.md
> +| frequency | string | 0s | Initial frequency of publishing system data to cloud as a sequence of decimal numbers, each with optional fraction and a unit suffix, such as: 300ms, 1.5h, 10m30s, etc., t
- could you please check the default value? I am not sure that there is such.
- "to cloud" should be removed. Eclipse Hono/Ditto can be deployed in different environments: cloud, on-premise etc.

2022-08-11 11:53 UTC, e-grigorov commented on web/site/content/docs/references/system-metrics-config.md
> +To control all aspects of the system metrics behavior.
Focus on the functionality, not the component name.

2022-08-11 11:53 UTC, e-grigorov commented on web/site/content/docs/references/system-metrics-config.md
> +The minimal required configuration that runs system metrics.
> runs system metrics

Run is not the main reason. The minimum configuration to activate.....

2022-08-11 11:53 UTC, e-grigorov commented on web/site/content/docs/references/system-metrics-config.md
> +"frequency": "60s"
Could you please apply a formatter. See the rest of the examples.

2022-08-11 14:08 UTC, e-grigorov requested changes

2022-08-11 14:08 UTC, e-grigorov commented on web/site/content/docs/references/system-metrics-config.md
> +    "frequency" : "0s"
Finally, is 0s a default value or not? It was removed from the table.

2022-08-11 14:31 UTC, gboyvalenkov-bosch commented on web/site/content/docs/references/system-metrics-config.md
> +    "frequency" : "0s"
Fixed

2022-08-11 14:44 UTC, e-grigorov requested changes

2022-08-11 14:44 UTC, e-grigorov commented on web/site/content/docs/references/system-metrics-config.md
> +The minimal required configuration that enables reporting of system metrics.
One final suggestion, the reporting can be enabled with a command or with this configuration property. The configuration property is more like auto-reporting. This sentence can be extend to: ...enables the auto-reporting...

2022-08-11 17:53 UTC, konstantina-gramatova requested changes

2022-08-11 17:53 UTC, konstantina-gramatova commented on web/site/content/docs/references/system-metrics-config.md
> +| frequency | string | | Initial frequency of reporting system metrics as a sequence of decimal numbers, each with optional fraction and a unit suffix, such as: 300ms, 1.5h, 10m30s, etc., time units
Could be simplified to:
Initial system metrics reporting frequency as a sequence of decimal numbers, each with an optional fraction and a unit...............

2022-08-12 06:53 UTC, e-grigorov approved these changes

2022-08-12 08:36 UTC, konstantina-gramatova approved these changes

2022-08-12 09:29 UTC, merged