Provide Reference guide for the Kanto Suite Bootstrapping
eclipse-kanto/kanto pull request #87
Opened 2022-08-12 12:29 UTC by gboyvalenkov-bosch

[#48] Provide Reference guide for the Kanto Suite Bootstrapping

- reference guide created

Signed-off-by: Georgi Boyvalenkov <Georgi.Boyvalenkov@bosch.io>

2022-08-15 07:14 UTC, e-grigorov requested changes

2022-08-15 07:14 UTC, e-grigorov commented on web/site/content/docs/references/suite-bootstrapping-config.md
> +| preBootstrapFile | string | | Pre-bootstrapping file |
We cannot just say that preBootstrappingFile is pre-bootstrapping file. It doesn't add value. We have to say that it's a file path and some more info about this file.

2022-08-15 07:14 UTC, e-grigorov commented on web/site/content/docs/references/suite-bootstrapping-config.md
> +| preBootstrapScript | script | | Pre-bootstrapping script, space separated arguments if any |
"script" - there is no such type. It should be "string" with some more descriptions.

2022-08-15 07:14 UTC, e-grigorov commented on web/site/content/docs/references/suite-bootstrapping-config.md
> +| postBootstrapFile | string | | Post-bootstrapping file |
We cannot just say that postBootstrappingFile is post-bootstrapping file. It doesn't add value. We have to say that it's a file path and some more info about this file.

2022-08-15 07:14 UTC, e-grigorov commented on web/site/content/docs/references/suite-bootstrapping-config.md
> +| bootstrapProvisioningFile | string | | Location where bootstrapping provisioning JSON result is stored |
It seems that the description need some refactoring. For example:
- "bootstrapping provisioning" doesn't sound correct
- "JSON result" - actually it's a file

2022-08-15 07:14 UTC, e-grigorov commented on web/site/content/docs/references/suite-bootstrapping-config.md
> +| maxChunkSize | int | 46080 | Maximum request chunk size in bytes |
We have to add that this is the chunk size of the request data.

2022-08-15 07:14 UTC, e-grigorov commented on web/site/content/docs/references/suite-bootstrapping-config.md
> +    "deviceId": "org.eclipse.kanto:exampleDevice",
- use the suite connector as a base for this example
- provisioning.json can be replaced by post-provisioning script

2022-08-15 07:14 UTC, e-grigorov commented on web/site/content/docs/references/suite-bootstrapping-config.md
> +The configuration can be further adjusted according to the use case.
Suite connector warning note is valid here.

2022-08-15 12:19 UTC, e-grigorov requested changes

2022-08-15 12:19 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/_index.md
> +weight: 2
The weight should be 1, why is it set to 2?

2022-08-15 12:19 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| address | string | mqtts://mqtt.bosch-iot-hub.com:8883 | Address of the MQTT endpoint that the suite connector will connect for the remote communication, the format is: `scheme://host:port` |
- "suite connector" should be "suite bootstrapping"
- "for the remote communication" cna be more context specific and related to the provisioning process

2022-08-15 12:19 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| cert | string | | A PEM encoded certificate file for cloud access |
The description can be aligned with the suite connector.

2022-08-15 12:19 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| key | string | | A PEM encoded unencrypted private key file for cloud access |
The description can be aligned with the suite connector.

2022-08-15 12:19 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| **Local connectivity** | | | |
Could you please double check the local connectivity. Suite bootstrapping should not have a local connectivity, nothing to do there.

2022-08-15 12:19 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| preBootstrapScript | string | | A file(s), containing pre-bootstrapping script(s), space separated arguments if any, executed before a bootstrapping request |
- Is it possible to have multiple pre-booting scripts?
- file path is mising

2022-08-15 12:19 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +    "provisioningFile": "provisioning.json",
The order should be the same as it's in the table above.

2022-08-16 11:47 UTC, e-grigorov requested changes

2022-08-16 11:47 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| preBootstrapScript | string | | Path to the file and space separated arguments if any, containing pre-bootstrapping script that is executed before a bootstrapping request, producing preBootstrapFil
- use code block in case of a reference to another property. File upload "context" property is a such example.
- content-wise seems correct but it's a little bit longer, what about: Path to the script/command with optional space-separated arguments, producing `preBootstrapFile` as output

2022-08-16 11:47 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| preBootstrapFile | string | | Path to the file, that is used for output of pre-bootstrapping script |
- the description should provide 1 sentence about the purpose of this property not how its value can be provided.
- do we need comma before "that"?

2022-08-16 11:47 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| postBootstrapScript | string | | Path to the file and space separated arguments if any, containing post-bootstrapping script that is executed after a bootstrapping request, producing postBootstrapF
- could you double that what this script does? Produce or consume of the file?
- align the wording based on the previous comment.

2022-08-16 11:47 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| postBootstrapFile | string | | Path to the file, that is used for output of post-bootstrapping script |
the same issue as it was for pre-bootstrapping file.

2022-08-16 11:47 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +The minimal required configuration that enables automatic provisioning.
Actually, this configuration will connect Eclipse Hono sandbox but will not enable the automatic provisioning. You need backend application. It has to be rephrased.

2022-08-16 11:47 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| bootstrapProvisioningFile | string | | A file path, where bootstrapping response data is stored as JSON |
- all other properties start without "a" or "the".
- the description is so generic, in the end that's the provisioning.json file of the suite connector.

2022-08-16 11:47 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +    "bootstrapProvisioningJson": "",
The property name doesn't match the table property name. Do we have Json as a suffix or not?

2022-08-17 09:43 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| preBootstrapFile | string | | Path to the file, that is used for output of pre-bootstrapping script |
The comment is still valid. That's the pre-bootstrapping file. It can be static for the system or can be produced by the script.

2022-08-17 09:55 UTC, e-grigorov requested changes

2022-08-17 09:55 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| preBootstrapScript | string | | Path to the script/command with optional space-separated arguments that is executed before a bootstrapping request, producing `preBootstrapFile` as output |
optionally producing

2022-08-17 09:55 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| postBootstrapScript | string | | Path to the file and space separated arguments if any, containing post-bootstrapping script that is executed after a bootstrapping request, producing postBootstrapF
This comment is still valid.

2022-08-17 09:55 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| postBootstrapFile | string | | Path to the file, that is used for output of post-bootstrapping script |
This comment is still valid.

2022-08-17 09:55 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| cacert | string | iothub.crt | A PEM encoded CA certificates file |
"A PEM encoded..." should be: PEM encoded...

2022-08-18 08:28 UTC, e-grigorov requested changes

2022-08-18 08:28 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| bootstrapProvisioningFile | string | | Path to the file, that stores provisioning info from bootstrapping response data |
- "from bootstrapping response data" - should be just: "from bootstrapping response" - the response contains two fields: provisioning info and additional data. The data is stored in postBootstrapFile. bootstrapProvisioningFile contains the provisioning information.
- "file, that" - should be: "file that"

2022-08-18 11:04 UTC, e-grigorov approved these changes

2022-08-18 11:16 UTC, e-grigorov requested changes

2022-08-18 11:16 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +| cacert | string | iothub.crt | PEM encoded CA certificates file |
I think that we have to take into consideration this ticket: eclipse-kanto/suite-bootstrapping#7

2022-08-18 11:32 UTC, e-grigorov requested changes

2022-08-18 11:32 UTC, e-grigorov commented on web/site/content/docs/references/connectivity/suite-bootstrapping-config.md
> +    "caCert": "/etc/suite-bootstrapping/iothub.crt",
caCert was made optional with eclipse-kanto/suite-connector#34 i.e. it can be removed from the example

2022-08-18 12:01 UTC, e-grigorov approved these changes

2022-08-22 08:37 UTC, e-grigorov commented
@gboyvalenkov-bosch The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-08-22 08:38 UTC, gboyvalenkov-bosch commented
> @gboyvalenkov-bosch The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances 😊
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

2022-08-23 12:03 UTC, konstantina-gramatova requested changes

2022-08-23 12:16 UTC, konstantina-gramatova approved these changes

2022-08-24 11:39 UTC, merged