Provide Reference guide for the Kanto Container Management
eclipse-kanto/kanto pull request #93
Opened 2022-08-23 15:20 UTC by antoniyatrifonova

[#71] Provide Reference guide for the Kanto Container Management

- Provide the reference guide for the container manager configuration
- Add an example of how to use this configuration
- Add a template with all possible configuration properties and their default values
- Fix the description of the network mode property

Signed-off-by: Trifonova Antonia <Antonia.Trifonova@bosch.io>

2022-08-24 11:43 UTC, e-grigorov commented
@antoniyatrifonova The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-08-24 11:58 UTC, e-grigorov requested changes

2022-08-24 11:58 UTC, e-grigorov commented on web/site/content/docs/references/containers/container-manager-config.md
> +| features | string[] | ContainerFactory, SoftwareUpdatable | Features that will be registered for the container manager digital twin, the possible values are: ContainerFactory, SoftwareUpdatable |
ContainerFactory, SoftwareUpdatable -> ContainerFactory and SoftwareUpdatable

2022-08-24 12:54 UTC, antoniyatrifonova commented
> @antoniyatrifonova The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances 😊
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

2022-08-25 07:10 UTC, e-grigorov approved these changes

2022-08-25 07:26 UTC, konstantina-gramatova approved these changes

2022-08-25 07:28 UTC, merged